-- =============================================================================
-- Seed data for local development
-- Generated by: npx tsx supabase/scripts/generate-seed.ts
-- Test user: admin@test.local / password123
--
-- DO NOT EDIT MANUALLY — regenerate with:
--   supabase db reset --no-seed
--   npx tsx supabase/scripts/generate-seed.ts
-- =============================================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: users; Type: TABLE DATA; Schema: auth; Owner: -
--

INSERT INTO auth.users VALUES ('00000000-0000-0000-0000-000000000000', 'a1d3b9ee-bcf6-47a8-8cca-4b0593018a23', 'authenticated', 'authenticated', 'admin@test.local', '$2a$10$O.d5k0hPTbuS0DV.wHXAyeJ23M50xS.KVeF1a3K8KlqkWSZ0EZPiG', '2026-03-27 17:35:32.392746+00', NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"], "employee_id": "4c8d114f-9763-4002-b3a1-f2f305b0b39c", "permissions": ["public_notices", "manage_employees"]}', '{"email_verified": true}', NULL, '2026-03-27 17:35:32.386349+00', '2026-03-27 17:35:32.459613+00', NULL, NULL, '', '', NULL, DEFAULT, '', 0, NULL, '', NULL, false, NULL, false);


--
-- Data for Name: identities; Type: TABLE DATA; Schema: auth; Owner: -
--

INSERT INTO auth.identities VALUES ('a1d3b9ee-bcf6-47a8-8cca-4b0593018a23', 'a1d3b9ee-bcf6-47a8-8cca-4b0593018a23', '{"sub": "a1d3b9ee-bcf6-47a8-8cca-4b0593018a23", "email": "admin@test.local", "email_verified": false, "phone_verified": false}', 'email', '2026-03-27 17:35:32.389429+00', '2026-03-27 17:35:32.389466+00', '2026-03-27 17:35:32.389466+00', DEFAULT, '0b0b54e8-ea20-48b9-9305-af1955b0cc1f');


--
-- Data for Name: instances; Type: TABLE DATA; Schema: auth; Owner: -
--



--
-- Data for Name: oauth_clients; Type: TABLE DATA; Schema: auth; Owner: -
--



--
-- Data for Name: oauth_authorizations; Type: TABLE DATA; Schema: auth; Owner: -
--



--
-- Data for Name: oauth_client_states; Type: TABLE DATA; Schema: auth; Owner: -
--



--
-- Data for Name: oauth_consents; Type: TABLE DATA; Schema: auth; Owner: -
--



--
-- Data for Name: zip_codes; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.zip_codes VALUES ('c822540e-702c-4589-a108-ea3c63836738', '08901', 'New Brunswick', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('4fffdf36-b190-48dc-ab82-0970975b8a90', '08902', 'North Brunswick', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('fff83405-cd88-4c73-a52b-324f13534fd3', '08903', 'New Brunswick', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('a1436506-920e-4629-80b8-eeb38cdcfe63', '08816', 'East Brunswick', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('f89af47a-e48c-4e48-92ac-cf2c37cbfd09', '08817', 'Edison', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('207d8e63-3ec6-4134-8ed0-6aa3c35a655f', '08820', 'Edison', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('1a8dccdd-1caa-4d67-9ccb-0b3294fb177f', '08837', 'Edison', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('faf29456-df72-4870-86d5-b2ffa36e69e0', '08840', 'Metuchen', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('ed575f02-b837-43f0-a0a7-a1c505815bea', '08846', 'Middlesex', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('4d5d706b-4c11-488a-a01f-67f83d7bd027', '08854', 'Piscataway', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('38856dc0-d118-45e8-b4ce-cb339d0a9f2a', '08855', 'Piscataway', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('1a2a73c2-a437-453a-b369-b2587a4cc877', '08857', 'Old Bridge', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('b6f30228-774a-4bcd-9899-0afb55274c4e', '08859', 'Parlin', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('370fbc76-e31d-4a17-ae09-b75f6932cea3', '08861', 'Perth Amboy', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('99a3ead0-3a1e-44c0-9ae5-dd52f23d6ca2', '08862', 'Perth Amboy', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('c1275c78-3590-4f3e-ab3a-c7d0bb98148b', '08863', 'Fords', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('75627837-57aa-41c2-b137-54bcef158f48', '08871', 'Sayreville', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('2947b168-84f4-4fcf-8405-d620f54fd477', '08872', 'Sayreville', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('7afad72d-18b3-4de9-a373-89847b5e64e6', '08879', 'South Amboy', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('572e2631-6ebf-4142-9bb5-6cc76dda89ed', '08882', 'South River', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('898bad1c-792d-4367-ab01-4d5dfa0ad698', '08884', 'Spotswood', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('da080bb1-d69c-42a8-9ae3-c046eb25d248', '08899', 'Edison', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('b8d3ba3e-45ed-46fe-98cb-fe9f6488defa', '07001', 'Avenel', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('71fbecd8-0841-43ba-b22b-d65ea5c7fc4c', '07064', 'Port Reading', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('3d34a65e-4e09-4e96-aa52-eb61527670d2', '07067', 'Colonia', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('b908fb99-3f4b-4163-8c45-8351dfb04569', '07077', 'Sewaren', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('46bd7995-6abd-4f61-ae09-0a51a6925f50', '07080', 'South Plainfield', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('a5d8a4c9-93ae-44f4-820b-81af18c2c061', '07095', 'Woodbridge', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('b81f8122-ebfa-4214-8263-73ff76b7291f', '08810', 'Dayton', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('d582c9b7-7a3e-4979-b606-ba4d854be6ad', '08812', 'Dunellen', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('fabfb990-dbd8-4113-a292-52f986d03e12', '08824', 'Kendall Park', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('350fcfea-16f9-43bb-8eba-2413fe4c9bcd', '08828', 'Helmetta', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('4459eabd-94c7-4720-9df1-1a82225b5ad5', '08830', 'Iselin', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('ffba4927-7a34-4894-8fb2-f97a79119fc8', '08831', 'Monroe Township', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('0238a0b5-74ce-4c29-a3ee-a56ed0e3b7c0', '08832', 'Jamesburg', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('28de8974-a015-42cb-af14-982f321b3e26', '08850', 'Milltown', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('c9491289-6fd1-4d7f-a63f-d2f74664fdd9', '08852', 'Monmouth Junction', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('edb522ec-9f98-44f9-bd68-8789d3655512', '07008', 'Carteret', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('8eb575ef-27ab-4450-bab3-09af77b14eca', '08536', 'Plainsboro', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);
INSERT INTO public.zip_codes VALUES ('0ae24455-358b-48f4-b858-c6f9c088a8ae', '08540', 'Princeton', 'NJ', '2026-03-27 17:35:32.516386+00', NULL, '2026-03-27 17:35:32.516386+00', NULL);


--
-- Data for Name: adult_mosquito_complaints; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.adult_mosquito_complaints VALUES ('fba41813-3af1-47ae-a6f6-809f3787473f', 'John Smith', '732-555-0100', 'john@example.com', '123 Main St', NULL, 'c822540e-702c-4589-a108-ea3c63836738', true, false, false, true, false, false, true, false, NULL, '2026-03-27 17:35:32.535316+00', NULL, '2026-03-27 17:35:32.535316+00', NULL);


--
-- Data for Name: contact_form_submissions; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.contact_form_submissions VALUES ('2bbbaef2-c5e6-406d-a8c2-6f685701a2f2', 'Jane Doe', 'jane@example.com', 'Question about spraying schedule', 'When will spraying occur in the 08901 area?', false, '2026-03-27 17:35:32.52826+00', NULL, '2026-03-27 17:35:32.52826+00', NULL);


--
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.employees VALUES ('4c8d114f-9763-4002-b3a1-f2f305b0b39c', 'admin@test.local', 'a1d3b9ee-bcf6-47a8-8cca-4b0593018a23', 'Test Admin', 'Administrator', '2026-03-27 17:35:32.426302+00', NULL, '2026-03-27 17:35:32.426302+00', NULL);
INSERT INTO public.employees VALUES ('e036f894-f92c-4ea1-a237-5c1b5bc2a3ad', 'unlinked@test.local', NULL, 'Unlinked Employee', NULL, '2026-03-27 17:35:32.442188+00', NULL, '2026-03-27 17:35:32.442188+00', NULL);


--
-- Data for Name: insecticides; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.insecticides VALUES ('1d8a4ebe-3c2a-4912-a0fd-059f6e46f47f', 'Larvicide', 'Bacillus thuringiensis israelensis (Bti)', 'https://example.com/bti', 'VectoBac 12AS', 'https://example.com/vectobac-label', 'https://example.com/vectobac-msds', '2026-03-27 17:35:32.509231+00', NULL, '2026-03-27 17:35:32.509231+00', NULL);
INSERT INTO public.insecticides VALUES ('b936d841-ee93-464c-9979-1e394b5f9e99', 'Adulticide', 'Sumithrin + PBO', 'https://example.com/sumithrin', 'Anvil 10+10 ULV', 'https://example.com/anvil-label', 'https://example.com/anvil-msds', '2026-03-27 17:35:32.509231+00', NULL, '2026-03-27 17:35:32.509231+00', NULL);
INSERT INTO public.insecticides VALUES ('54189dc2-e018-428b-a3cb-f4156266cdfb', 'Larvicide', 'Methoprene', 'https://example.com/methoprene', 'Altosid Pellets', 'https://example.com/altosid-label', 'https://example.com/altosid-msds', '2026-03-27 17:35:32.509231+00', NULL, '2026-03-27 17:35:32.509231+00', NULL);


--
-- Data for Name: meetings; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.meetings VALUES ('d262cc18-bfbb-47f5-9f16-ac1f2d88ab28', 'Regular Commission Meeting', '2026-04-09 19:00:00+00', false, NULL, NULL, NULL, '2026-03-27 17:35:32.499476+00', NULL, '2026-03-27 17:35:32.499476+00', NULL, '1 JFK Blvd, New Brunswick, NJ', NULL, NULL);
INSERT INTO public.meetings VALUES ('cfa5d743-112c-4f95-926f-6136be3eb9ed', 'Regular Commission Meeting', '2026-05-14 19:00:00+00', false, NULL, NULL, NULL, '2026-03-27 17:35:32.499476+00', NULL, '2026-03-27 17:35:32.499476+00', NULL, '1 JFK Blvd, New Brunswick, NJ', NULL, NULL);
INSERT INTO public.meetings VALUES ('45ab4ac5-dee7-4ca2-b53e-77fac1a0f4a9', 'Special Budget Meeting', '2026-04-23 18:00:00+00', false, NULL, NULL, NULL, '2026-03-27 17:35:32.499476+00', NULL, '2026-03-27 17:35:32.499476+00', NULL, '1 JFK Blvd, New Brunswick, NJ', NULL, NULL);


--
-- Data for Name: mosquito_fish_requests; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.mosquito_fish_requests VALUES ('f3fabc31-b055-40f2-83f1-9aecbc74f6e4', 'Maria Garcia', '732-555-0200', 'maria@example.com', '456 Oak Ave', NULL, 'a1436506-920e-4629-80b8-eeb38cdcfe63', 'Backyard pond near fence line', 'Pond', false, NULL, '2026-03-27 17:35:32.542147+00', NULL, '2026-03-27 17:35:32.542147+00', NULL);


--
-- Data for Name: notice_types; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.notice_types VALUES ('d71f5059-54d6-4825-801f-754b6e74977c', 'General', 'General public notices', '2026-03-27 17:35:32.469813+00', NULL, '2026-03-27 17:35:32.469813+00', NULL);
INSERT INTO public.notice_types VALUES ('db4034bd-4772-4af6-adaf-9049ddca1661', 'Spraying', 'Mosquito spraying schedule notices', '2026-03-27 17:35:32.469813+00', NULL, '2026-03-27 17:35:32.469813+00', NULL);
INSERT INTO public.notice_types VALUES ('69aee244-35ea-455b-afdc-686d4bf096da', 'Meeting', 'Commission meeting notices', '2026-03-27 17:35:32.469813+00', NULL, '2026-03-27 17:35:32.469813+00', NULL);
INSERT INTO public.notice_types VALUES ('cd95e30f-552b-465b-a1b1-14516ce97f69', 'Advisory', 'Public health advisories', '2026-03-27 17:35:32.469813+00', NULL, '2026-03-27 17:35:32.469813+00', NULL);


--
-- Data for Name: notices; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.notices VALUES ('08e3fbd2-2718-4907-b91e-213186c5d7a1', 'db4034bd-4772-4af6-adaf-9049ddca1661', 'Aerial Spraying Scheduled — North District', '{"type": "doc", "content": [{"type": "paragraph", "content": [{"text": "Aerial spraying for adult mosquitoes will take place in the North District on the evening of March 28. Residents are advised to stay indoors during application.", "type": "text"}]}]}', '2026-03-27 17:35:32.489794+00', NULL, '2026-03-27 17:35:32.489794+00', NULL, '2026-03-28', true, false);
INSERT INTO public.notices VALUES ('f38a9db8-0609-41d5-a308-c77dc5f4f3f1', 'd71f5059-54d6-4825-801f-754b6e74977c', 'Seasonal Reminder: Eliminate Standing Water', '{"type": "doc", "content": [{"type": "paragraph", "content": [{"text": "As warmer weather approaches, please remove any standing water sources around your property to help reduce mosquito breeding.", "type": "text"}]}]}', '2026-03-27 17:35:32.489794+00', NULL, '2026-03-27 17:35:32.489794+00', NULL, '2026-03-15', true, false);
INSERT INTO public.notices VALUES ('654c841f-e766-4b63-9c87-940285f94faf', 'cd95e30f-552b-465b-a1b1-14516ce97f69', 'West Nile Virus Activity Detected', '{"type": "doc", "content": [{"type": "paragraph", "content": [{"text": "West Nile Virus has been detected in mosquito samples collected from the South District. Take precautions to avoid mosquito bites.", "type": "text"}]}]}', '2026-03-27 17:35:32.489794+00', NULL, '2026-03-27 17:35:32.489794+00', NULL, '2026-04-01', false, false);


--
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.permissions VALUES ('9b93e6fb-89f0-4017-a618-c0c2b3c3c14e', 'public_notices', '2026-03-27 17:35:32.450567+00', 'Manage public notices, meetings, insecticides, and service requests');
INSERT INTO public.permissions VALUES ('510ed8eb-c411-48f0-bfa2-b2117c85a3d3', 'manage_employees', '2026-03-27 17:35:32.450567+00', 'Manage employee records and send account invites');


--
-- Data for Name: user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.user_permissions VALUES ('503248bb-21f2-4c84-aa76-c9bc5d03a3cc', 'a1d3b9ee-bcf6-47a8-8cca-4b0593018a23', '2026-03-27 17:35:32.459613+00', NULL, 'public_notices');
INSERT INTO public.user_permissions VALUES ('4bfbb4b3-0ecc-4ebb-8f38-2d9dc8005ba1', 'a1d3b9ee-bcf6-47a8-8cca-4b0593018a23', '2026-03-27 17:35:32.459613+00', NULL, 'manage_employees');


--
-- Data for Name: water_management_requests; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.water_management_requests VALUES ('fdec9a1f-77ce-4af8-97a8-6770bd8c1728', 'Bob Johnson', '732-555-0300', 'bob@example.com', '789 Elm St', NULL, '4d5d706b-4c11-488a-a01f-67f83d7bd027', false, false, true, 'Drainage ditch along Cedar Lane', false, NULL, '2026-03-27 17:35:32.549179+00', NULL, '2026-03-27 17:35:32.549179+00', NULL);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE SET; Schema: auth; Owner: -
--

SELECT pg_catalog.setval('auth.refresh_tokens_id_seq', 1, false);


--
-- PostgreSQL database dump complete
--


