/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appCategoriesRouteImport } from './routes/(app)/categories'
import { Route as appServiceRequestsRouteRouteImport } from './routes/(app)/service-requests/route'
import { Route as appNoticesRouteRouteImport } from './routes/(app)/notices/route'
import { Route as appMeetingsRouteRouteImport } from './routes/(app)/meetings/route'
import { Route as appInsecticidesRouteRouteImport } from './routes/(app)/insecticides/route'
import { Route as appContactSubmissionsRouteRouteImport } from './routes/(app)/contact-submissions/route'
import { Route as appServiceRequestsIndexRouteImport } from './routes/(app)/service-requests/index'
import { Route as appNoticesIndexRouteImport } from './routes/(app)/notices/index'
import { Route as appMeetingsIndexRouteImport } from './routes/(app)/meetings/index'
import { Route as appInsecticidesIndexRouteImport } from './routes/(app)/insecticides/index'
import { Route as appContactSubmissionsIndexRouteImport } from './routes/(app)/contact-submissions/index'
import { Route as appNoticesCreateRouteImport } from './routes/(app)/notices/create'
import { Route as appNoticesNoticeIdRouteImport } from './routes/(app)/notices/$noticeId'
import { Route as appMeetingsCreateRouteImport } from './routes/(app)/meetings/create'
import { Route as appMeetingsMeetingIdRouteImport } from './routes/(app)/meetings/$meetingId'
import { Route as appInsecticidesCreateRouteImport } from './routes/(app)/insecticides/create'
import { Route as appInsecticidesInsecticideIdRouteImport } from './routes/(app)/insecticides/$insecticideId'
import { Route as appContactSubmissionsCreateRouteImport } from './routes/(app)/contact-submissions/create'
import { Route as appContactSubmissionsSubmissionIdRouteImport } from './routes/(app)/contact-submissions/$submissionId'
import { Route as appServiceRequestsWaterManagementCreateRouteImport } from './routes/(app)/service-requests/water-management/create'
import { Route as appServiceRequestsWaterManagementRequestIdRouteImport } from './routes/(app)/service-requests/water-management/$requestId'
import { Route as appServiceRequestsMosquitofishCreateRouteImport } from './routes/(app)/service-requests/mosquitofish/create'
import { Route as appServiceRequestsMosquitofishRequestIdRouteImport } from './routes/(app)/service-requests/mosquitofish/$requestId'
import { Route as appServiceRequestsAdultMosquitoCreateRouteImport } from './routes/(app)/service-requests/adult-mosquito/create'
import { Route as appServiceRequestsAdultMosquitoRequestIdRouteImport } from './routes/(app)/service-requests/adult-mosquito/$requestId'
import { Route as appNoticesNoticeIdEditRouteImport } from './routes/(app)/notices/$noticeId_.edit'
import { Route as appContactSubmissionsSubmissionIdEditRouteImport } from './routes/(app)/contact-submissions/$submissionId_.edit'
import { Route as appServiceRequestsWaterManagementRequestIdEditRouteImport } from './routes/(app)/service-requests/water-management/$requestId_.edit'
import { Route as appServiceRequestsMosquitofishRequestIdEditRouteImport } from './routes/(app)/service-requests/mosquitofish/$requestId_.edit'
import { Route as appServiceRequestsAdultMosquitoRequestIdEditRouteImport } from './routes/(app)/service-requests/adult-mosquito/$requestId_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCategoriesRoute = appCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => appRouteRoute,
} as any)
const appServiceRequestsRouteRoute = appServiceRequestsRouteRouteImport.update({
  id: '/service-requests',
  path: '/service-requests',
  getParentRoute: () => appRouteRoute,
} as any)
const appNoticesRouteRoute = appNoticesRouteRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => appRouteRoute,
} as any)
const appMeetingsRouteRoute = appMeetingsRouteRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => appRouteRoute,
} as any)
const appInsecticidesRouteRoute = appInsecticidesRouteRouteImport.update({
  id: '/insecticides',
  path: '/insecticides',
  getParentRoute: () => appRouteRoute,
} as any)
const appContactSubmissionsRouteRoute =
  appContactSubmissionsRouteRouteImport.update({
    id: '/contact-submissions',
    path: '/contact-submissions',
    getParentRoute: () => appRouteRoute,
  } as any)
const appServiceRequestsIndexRoute = appServiceRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appServiceRequestsRouteRoute,
} as any)
const appNoticesIndexRoute = appNoticesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appMeetingsIndexRoute = appMeetingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appMeetingsRouteRoute,
} as any)
const appInsecticidesIndexRoute = appInsecticidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appInsecticidesRouteRoute,
} as any)
const appContactSubmissionsIndexRoute =
  appContactSubmissionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appContactSubmissionsRouteRoute,
  } as any)
const appNoticesCreateRoute = appNoticesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appNoticesNoticeIdRoute = appNoticesNoticeIdRouteImport.update({
  id: '/$noticeId',
  path: '/$noticeId',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appMeetingsCreateRoute = appMeetingsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appMeetingsRouteRoute,
} as any)
const appMeetingsMeetingIdRoute = appMeetingsMeetingIdRouteImport.update({
  id: '/$meetingId',
  path: '/$meetingId',
  getParentRoute: () => appMeetingsRouteRoute,
} as any)
const appInsecticidesCreateRoute = appInsecticidesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appInsecticidesRouteRoute,
} as any)
const appInsecticidesInsecticideIdRoute =
  appInsecticidesInsecticideIdRouteImport.update({
    id: '/$insecticideId',
    path: '/$insecticideId',
    getParentRoute: () => appInsecticidesRouteRoute,
  } as any)
const appContactSubmissionsCreateRoute =
  appContactSubmissionsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => appContactSubmissionsRouteRoute,
  } as any)
const appContactSubmissionsSubmissionIdRoute =
  appContactSubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => appContactSubmissionsRouteRoute,
  } as any)
const appServiceRequestsWaterManagementCreateRoute =
  appServiceRequestsWaterManagementCreateRouteImport.update({
    id: '/water-management/create',
    path: '/water-management/create',
    getParentRoute: () => appServiceRequestsRouteRoute,
  } as any)
const appServiceRequestsWaterManagementRequestIdRoute =
  appServiceRequestsWaterManagementRequestIdRouteImport.update({
    id: '/water-management/$requestId',
    path: '/water-management/$requestId',
    getParentRoute: () => appServiceRequestsRouteRoute,
  } as any)
const appServiceRequestsMosquitofishCreateRoute =
  appServiceRequestsMosquitofishCreateRouteImport.update({
    id: '/mosquitofish/create',
    path: '/mosquitofish/create',
    getParentRoute: () => appServiceRequestsRouteRoute,
  } as any)
const appServiceRequestsMosquitofishRequestIdRoute =
  appServiceRequestsMosquitofishRequestIdRouteImport.update({
    id: '/mosquitofish/$requestId',
    path: '/mosquitofish/$requestId',
    getParentRoute: () => appServiceRequestsRouteRoute,
  } as any)
const appServiceRequestsAdultMosquitoCreateRoute =
  appServiceRequestsAdultMosquitoCreateRouteImport.update({
    id: '/adult-mosquito/create',
    path: '/adult-mosquito/create',
    getParentRoute: () => appServiceRequestsRouteRoute,
  } as any)
const appServiceRequestsAdultMosquitoRequestIdRoute =
  appServiceRequestsAdultMosquitoRequestIdRouteImport.update({
    id: '/adult-mosquito/$requestId',
    path: '/adult-mosquito/$requestId',
    getParentRoute: () => appServiceRequestsRouteRoute,
  } as any)
const appNoticesNoticeIdEditRoute = appNoticesNoticeIdEditRouteImport.update({
  id: '/$noticeId_/edit',
  path: '/$noticeId/edit',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appContactSubmissionsSubmissionIdEditRoute =
  appContactSubmissionsSubmissionIdEditRouteImport.update({
    id: '/$submissionId_/edit',
    path: '/$submissionId/edit',
    getParentRoute: () => appContactSubmissionsRouteRoute,
  } as any)
const appServiceRequestsWaterManagementRequestIdEditRoute =
  appServiceRequestsWaterManagementRequestIdEditRouteImport.update({
    id: '/water-management/$requestId_/edit',
    path: '/water-management/$requestId/edit',
    getParentRoute: () => appServiceRequestsRouteRoute,
  } as any)
const appServiceRequestsMosquitofishRequestIdEditRoute =
  appServiceRequestsMosquitofishRequestIdEditRouteImport.update({
    id: '/mosquitofish/$requestId_/edit',
    path: '/mosquitofish/$requestId/edit',
    getParentRoute: () => appServiceRequestsRouteRoute,
  } as any)
const appServiceRequestsAdultMosquitoRequestIdEditRoute =
  appServiceRequestsAdultMosquitoRequestIdEditRouteImport.update({
    id: '/adult-mosquito/$requestId_/edit',
    path: '/adult-mosquito/$requestId/edit',
    getParentRoute: () => appServiceRequestsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/contact-submissions': typeof appContactSubmissionsRouteRouteWithChildren
  '/insecticides': typeof appInsecticidesRouteRouteWithChildren
  '/meetings': typeof appMeetingsRouteRouteWithChildren
  '/notices': typeof appNoticesRouteRouteWithChildren
  '/service-requests': typeof appServiceRequestsRouteRouteWithChildren
  '/categories': typeof appCategoriesRoute
  '/': typeof appIndexRoute
  '/contact-submissions/$submissionId': typeof appContactSubmissionsSubmissionIdRoute
  '/contact-submissions/create': typeof appContactSubmissionsCreateRoute
  '/insecticides/$insecticideId': typeof appInsecticidesInsecticideIdRoute
  '/insecticides/create': typeof appInsecticidesCreateRoute
  '/meetings/$meetingId': typeof appMeetingsMeetingIdRoute
  '/meetings/create': typeof appMeetingsCreateRoute
  '/notices/$noticeId': typeof appNoticesNoticeIdRoute
  '/notices/create': typeof appNoticesCreateRoute
  '/contact-submissions/': typeof appContactSubmissionsIndexRoute
  '/insecticides/': typeof appInsecticidesIndexRoute
  '/meetings/': typeof appMeetingsIndexRoute
  '/notices/': typeof appNoticesIndexRoute
  '/service-requests/': typeof appServiceRequestsIndexRoute
  '/contact-submissions/$submissionId/edit': typeof appContactSubmissionsSubmissionIdEditRoute
  '/notices/$noticeId/edit': typeof appNoticesNoticeIdEditRoute
  '/service-requests/adult-mosquito/$requestId': typeof appServiceRequestsAdultMosquitoRequestIdRoute
  '/service-requests/adult-mosquito/create': typeof appServiceRequestsAdultMosquitoCreateRoute
  '/service-requests/mosquitofish/$requestId': typeof appServiceRequestsMosquitofishRequestIdRoute
  '/service-requests/mosquitofish/create': typeof appServiceRequestsMosquitofishCreateRoute
  '/service-requests/water-management/$requestId': typeof appServiceRequestsWaterManagementRequestIdRoute
  '/service-requests/water-management/create': typeof appServiceRequestsWaterManagementCreateRoute
  '/service-requests/adult-mosquito/$requestId/edit': typeof appServiceRequestsAdultMosquitoRequestIdEditRoute
  '/service-requests/mosquitofish/$requestId/edit': typeof appServiceRequestsMosquitofishRequestIdEditRoute
  '/service-requests/water-management/$requestId/edit': typeof appServiceRequestsWaterManagementRequestIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/categories': typeof appCategoriesRoute
  '/': typeof appIndexRoute
  '/contact-submissions/$submissionId': typeof appContactSubmissionsSubmissionIdRoute
  '/contact-submissions/create': typeof appContactSubmissionsCreateRoute
  '/insecticides/$insecticideId': typeof appInsecticidesInsecticideIdRoute
  '/insecticides/create': typeof appInsecticidesCreateRoute
  '/meetings/$meetingId': typeof appMeetingsMeetingIdRoute
  '/meetings/create': typeof appMeetingsCreateRoute
  '/notices/$noticeId': typeof appNoticesNoticeIdRoute
  '/notices/create': typeof appNoticesCreateRoute
  '/contact-submissions': typeof appContactSubmissionsIndexRoute
  '/insecticides': typeof appInsecticidesIndexRoute
  '/meetings': typeof appMeetingsIndexRoute
  '/notices': typeof appNoticesIndexRoute
  '/service-requests': typeof appServiceRequestsIndexRoute
  '/contact-submissions/$submissionId/edit': typeof appContactSubmissionsSubmissionIdEditRoute
  '/notices/$noticeId/edit': typeof appNoticesNoticeIdEditRoute
  '/service-requests/adult-mosquito/$requestId': typeof appServiceRequestsAdultMosquitoRequestIdRoute
  '/service-requests/adult-mosquito/create': typeof appServiceRequestsAdultMosquitoCreateRoute
  '/service-requests/mosquitofish/$requestId': typeof appServiceRequestsMosquitofishRequestIdRoute
  '/service-requests/mosquitofish/create': typeof appServiceRequestsMosquitofishCreateRoute
  '/service-requests/water-management/$requestId': typeof appServiceRequestsWaterManagementRequestIdRoute
  '/service-requests/water-management/create': typeof appServiceRequestsWaterManagementCreateRoute
  '/service-requests/adult-mosquito/$requestId/edit': typeof appServiceRequestsAdultMosquitoRequestIdEditRoute
  '/service-requests/mosquitofish/$requestId/edit': typeof appServiceRequestsMosquitofishRequestIdEditRoute
  '/service-requests/water-management/$requestId/edit': typeof appServiceRequestsWaterManagementRequestIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(app)/contact-submissions': typeof appContactSubmissionsRouteRouteWithChildren
  '/(app)/insecticides': typeof appInsecticidesRouteRouteWithChildren
  '/(app)/meetings': typeof appMeetingsRouteRouteWithChildren
  '/(app)/notices': typeof appNoticesRouteRouteWithChildren
  '/(app)/service-requests': typeof appServiceRequestsRouteRouteWithChildren
  '/(app)/categories': typeof appCategoriesRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/contact-submissions/$submissionId': typeof appContactSubmissionsSubmissionIdRoute
  '/(app)/contact-submissions/create': typeof appContactSubmissionsCreateRoute
  '/(app)/insecticides/$insecticideId': typeof appInsecticidesInsecticideIdRoute
  '/(app)/insecticides/create': typeof appInsecticidesCreateRoute
  '/(app)/meetings/$meetingId': typeof appMeetingsMeetingIdRoute
  '/(app)/meetings/create': typeof appMeetingsCreateRoute
  '/(app)/notices/$noticeId': typeof appNoticesNoticeIdRoute
  '/(app)/notices/create': typeof appNoticesCreateRoute
  '/(app)/contact-submissions/': typeof appContactSubmissionsIndexRoute
  '/(app)/insecticides/': typeof appInsecticidesIndexRoute
  '/(app)/meetings/': typeof appMeetingsIndexRoute
  '/(app)/notices/': typeof appNoticesIndexRoute
  '/(app)/service-requests/': typeof appServiceRequestsIndexRoute
  '/(app)/contact-submissions/$submissionId_/edit': typeof appContactSubmissionsSubmissionIdEditRoute
  '/(app)/notices/$noticeId_/edit': typeof appNoticesNoticeIdEditRoute
  '/(app)/service-requests/adult-mosquito/$requestId': typeof appServiceRequestsAdultMosquitoRequestIdRoute
  '/(app)/service-requests/adult-mosquito/create': typeof appServiceRequestsAdultMosquitoCreateRoute
  '/(app)/service-requests/mosquitofish/$requestId': typeof appServiceRequestsMosquitofishRequestIdRoute
  '/(app)/service-requests/mosquitofish/create': typeof appServiceRequestsMosquitofishCreateRoute
  '/(app)/service-requests/water-management/$requestId': typeof appServiceRequestsWaterManagementRequestIdRoute
  '/(app)/service-requests/water-management/create': typeof appServiceRequestsWaterManagementCreateRoute
  '/(app)/service-requests/adult-mosquito/$requestId_/edit': typeof appServiceRequestsAdultMosquitoRequestIdEditRoute
  '/(app)/service-requests/mosquitofish/$requestId_/edit': typeof appServiceRequestsMosquitofishRequestIdEditRoute
  '/(app)/service-requests/water-management/$requestId_/edit': typeof appServiceRequestsWaterManagementRequestIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/contact-submissions'
    | '/insecticides'
    | '/meetings'
    | '/notices'
    | '/service-requests'
    | '/categories'
    | '/'
    | '/contact-submissions/$submissionId'
    | '/contact-submissions/create'
    | '/insecticides/$insecticideId'
    | '/insecticides/create'
    | '/meetings/$meetingId'
    | '/meetings/create'
    | '/notices/$noticeId'
    | '/notices/create'
    | '/contact-submissions/'
    | '/insecticides/'
    | '/meetings/'
    | '/notices/'
    | '/service-requests/'
    | '/contact-submissions/$submissionId/edit'
    | '/notices/$noticeId/edit'
    | '/service-requests/adult-mosquito/$requestId'
    | '/service-requests/adult-mosquito/create'
    | '/service-requests/mosquitofish/$requestId'
    | '/service-requests/mosquitofish/create'
    | '/service-requests/water-management/$requestId'
    | '/service-requests/water-management/create'
    | '/service-requests/adult-mosquito/$requestId/edit'
    | '/service-requests/mosquitofish/$requestId/edit'
    | '/service-requests/water-management/$requestId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/categories'
    | '/'
    | '/contact-submissions/$submissionId'
    | '/contact-submissions/create'
    | '/insecticides/$insecticideId'
    | '/insecticides/create'
    | '/meetings/$meetingId'
    | '/meetings/create'
    | '/notices/$noticeId'
    | '/notices/create'
    | '/contact-submissions'
    | '/insecticides'
    | '/meetings'
    | '/notices'
    | '/service-requests'
    | '/contact-submissions/$submissionId/edit'
    | '/notices/$noticeId/edit'
    | '/service-requests/adult-mosquito/$requestId'
    | '/service-requests/adult-mosquito/create'
    | '/service-requests/mosquitofish/$requestId'
    | '/service-requests/mosquitofish/create'
    | '/service-requests/water-management/$requestId'
    | '/service-requests/water-management/create'
    | '/service-requests/adult-mosquito/$requestId/edit'
    | '/service-requests/mosquitofish/$requestId/edit'
    | '/service-requests/water-management/$requestId/edit'
  id:
    | '__root__'
    | '/(app)'
    | '/login'
    | '/(app)/contact-submissions'
    | '/(app)/insecticides'
    | '/(app)/meetings'
    | '/(app)/notices'
    | '/(app)/service-requests'
    | '/(app)/categories'
    | '/(app)/'
    | '/(app)/contact-submissions/$submissionId'
    | '/(app)/contact-submissions/create'
    | '/(app)/insecticides/$insecticideId'
    | '/(app)/insecticides/create'
    | '/(app)/meetings/$meetingId'
    | '/(app)/meetings/create'
    | '/(app)/notices/$noticeId'
    | '/(app)/notices/create'
    | '/(app)/contact-submissions/'
    | '/(app)/insecticides/'
    | '/(app)/meetings/'
    | '/(app)/notices/'
    | '/(app)/service-requests/'
    | '/(app)/contact-submissions/$submissionId_/edit'
    | '/(app)/notices/$noticeId_/edit'
    | '/(app)/service-requests/adult-mosquito/$requestId'
    | '/(app)/service-requests/adult-mosquito/create'
    | '/(app)/service-requests/mosquitofish/$requestId'
    | '/(app)/service-requests/mosquitofish/create'
    | '/(app)/service-requests/water-management/$requestId'
    | '/(app)/service-requests/water-management/create'
    | '/(app)/service-requests/adult-mosquito/$requestId_/edit'
    | '/(app)/service-requests/mosquitofish/$requestId_/edit'
    | '/(app)/service-requests/water-management/$requestId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/categories': {
      id: '/(app)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof appCategoriesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/service-requests': {
      id: '/(app)/service-requests'
      path: '/service-requests'
      fullPath: '/service-requests'
      preLoaderRoute: typeof appServiceRequestsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/notices': {
      id: '/(app)/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof appNoticesRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/meetings': {
      id: '/(app)/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof appMeetingsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/insecticides': {
      id: '/(app)/insecticides'
      path: '/insecticides'
      fullPath: '/insecticides'
      preLoaderRoute: typeof appInsecticidesRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/contact-submissions': {
      id: '/(app)/contact-submissions'
      path: '/contact-submissions'
      fullPath: '/contact-submissions'
      preLoaderRoute: typeof appContactSubmissionsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/service-requests/': {
      id: '/(app)/service-requests/'
      path: '/'
      fullPath: '/service-requests/'
      preLoaderRoute: typeof appServiceRequestsIndexRouteImport
      parentRoute: typeof appServiceRequestsRouteRoute
    }
    '/(app)/notices/': {
      id: '/(app)/notices/'
      path: '/'
      fullPath: '/notices/'
      preLoaderRoute: typeof appNoticesIndexRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/meetings/': {
      id: '/(app)/meetings/'
      path: '/'
      fullPath: '/meetings/'
      preLoaderRoute: typeof appMeetingsIndexRouteImport
      parentRoute: typeof appMeetingsRouteRoute
    }
    '/(app)/insecticides/': {
      id: '/(app)/insecticides/'
      path: '/'
      fullPath: '/insecticides/'
      preLoaderRoute: typeof appInsecticidesIndexRouteImport
      parentRoute: typeof appInsecticidesRouteRoute
    }
    '/(app)/contact-submissions/': {
      id: '/(app)/contact-submissions/'
      path: '/'
      fullPath: '/contact-submissions/'
      preLoaderRoute: typeof appContactSubmissionsIndexRouteImport
      parentRoute: typeof appContactSubmissionsRouteRoute
    }
    '/(app)/notices/create': {
      id: '/(app)/notices/create'
      path: '/create'
      fullPath: '/notices/create'
      preLoaderRoute: typeof appNoticesCreateRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/notices/$noticeId': {
      id: '/(app)/notices/$noticeId'
      path: '/$noticeId'
      fullPath: '/notices/$noticeId'
      preLoaderRoute: typeof appNoticesNoticeIdRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/meetings/create': {
      id: '/(app)/meetings/create'
      path: '/create'
      fullPath: '/meetings/create'
      preLoaderRoute: typeof appMeetingsCreateRouteImport
      parentRoute: typeof appMeetingsRouteRoute
    }
    '/(app)/meetings/$meetingId': {
      id: '/(app)/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof appMeetingsMeetingIdRouteImport
      parentRoute: typeof appMeetingsRouteRoute
    }
    '/(app)/insecticides/create': {
      id: '/(app)/insecticides/create'
      path: '/create'
      fullPath: '/insecticides/create'
      preLoaderRoute: typeof appInsecticidesCreateRouteImport
      parentRoute: typeof appInsecticidesRouteRoute
    }
    '/(app)/insecticides/$insecticideId': {
      id: '/(app)/insecticides/$insecticideId'
      path: '/$insecticideId'
      fullPath: '/insecticides/$insecticideId'
      preLoaderRoute: typeof appInsecticidesInsecticideIdRouteImport
      parentRoute: typeof appInsecticidesRouteRoute
    }
    '/(app)/contact-submissions/create': {
      id: '/(app)/contact-submissions/create'
      path: '/create'
      fullPath: '/contact-submissions/create'
      preLoaderRoute: typeof appContactSubmissionsCreateRouteImport
      parentRoute: typeof appContactSubmissionsRouteRoute
    }
    '/(app)/contact-submissions/$submissionId': {
      id: '/(app)/contact-submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/contact-submissions/$submissionId'
      preLoaderRoute: typeof appContactSubmissionsSubmissionIdRouteImport
      parentRoute: typeof appContactSubmissionsRouteRoute
    }
    '/(app)/service-requests/water-management/create': {
      id: '/(app)/service-requests/water-management/create'
      path: '/water-management/create'
      fullPath: '/service-requests/water-management/create'
      preLoaderRoute: typeof appServiceRequestsWaterManagementCreateRouteImport
      parentRoute: typeof appServiceRequestsRouteRoute
    }
    '/(app)/service-requests/water-management/$requestId': {
      id: '/(app)/service-requests/water-management/$requestId'
      path: '/water-management/$requestId'
      fullPath: '/service-requests/water-management/$requestId'
      preLoaderRoute: typeof appServiceRequestsWaterManagementRequestIdRouteImport
      parentRoute: typeof appServiceRequestsRouteRoute
    }
    '/(app)/service-requests/mosquitofish/create': {
      id: '/(app)/service-requests/mosquitofish/create'
      path: '/mosquitofish/create'
      fullPath: '/service-requests/mosquitofish/create'
      preLoaderRoute: typeof appServiceRequestsMosquitofishCreateRouteImport
      parentRoute: typeof appServiceRequestsRouteRoute
    }
    '/(app)/service-requests/mosquitofish/$requestId': {
      id: '/(app)/service-requests/mosquitofish/$requestId'
      path: '/mosquitofish/$requestId'
      fullPath: '/service-requests/mosquitofish/$requestId'
      preLoaderRoute: typeof appServiceRequestsMosquitofishRequestIdRouteImport
      parentRoute: typeof appServiceRequestsRouteRoute
    }
    '/(app)/service-requests/adult-mosquito/create': {
      id: '/(app)/service-requests/adult-mosquito/create'
      path: '/adult-mosquito/create'
      fullPath: '/service-requests/adult-mosquito/create'
      preLoaderRoute: typeof appServiceRequestsAdultMosquitoCreateRouteImport
      parentRoute: typeof appServiceRequestsRouteRoute
    }
    '/(app)/service-requests/adult-mosquito/$requestId': {
      id: '/(app)/service-requests/adult-mosquito/$requestId'
      path: '/adult-mosquito/$requestId'
      fullPath: '/service-requests/adult-mosquito/$requestId'
      preLoaderRoute: typeof appServiceRequestsAdultMosquitoRequestIdRouteImport
      parentRoute: typeof appServiceRequestsRouteRoute
    }
    '/(app)/notices/$noticeId_/edit': {
      id: '/(app)/notices/$noticeId_/edit'
      path: '/$noticeId/edit'
      fullPath: '/notices/$noticeId/edit'
      preLoaderRoute: typeof appNoticesNoticeIdEditRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/contact-submissions/$submissionId_/edit': {
      id: '/(app)/contact-submissions/$submissionId_/edit'
      path: '/$submissionId/edit'
      fullPath: '/contact-submissions/$submissionId/edit'
      preLoaderRoute: typeof appContactSubmissionsSubmissionIdEditRouteImport
      parentRoute: typeof appContactSubmissionsRouteRoute
    }
    '/(app)/service-requests/water-management/$requestId_/edit': {
      id: '/(app)/service-requests/water-management/$requestId_/edit'
      path: '/water-management/$requestId/edit'
      fullPath: '/service-requests/water-management/$requestId/edit'
      preLoaderRoute: typeof appServiceRequestsWaterManagementRequestIdEditRouteImport
      parentRoute: typeof appServiceRequestsRouteRoute
    }
    '/(app)/service-requests/mosquitofish/$requestId_/edit': {
      id: '/(app)/service-requests/mosquitofish/$requestId_/edit'
      path: '/mosquitofish/$requestId/edit'
      fullPath: '/service-requests/mosquitofish/$requestId/edit'
      preLoaderRoute: typeof appServiceRequestsMosquitofishRequestIdEditRouteImport
      parentRoute: typeof appServiceRequestsRouteRoute
    }
    '/(app)/service-requests/adult-mosquito/$requestId_/edit': {
      id: '/(app)/service-requests/adult-mosquito/$requestId_/edit'
      path: '/adult-mosquito/$requestId/edit'
      fullPath: '/service-requests/adult-mosquito/$requestId/edit'
      preLoaderRoute: typeof appServiceRequestsAdultMosquitoRequestIdEditRouteImport
      parentRoute: typeof appServiceRequestsRouteRoute
    }
  }
}

interface appContactSubmissionsRouteRouteChildren {
  appContactSubmissionsSubmissionIdRoute: typeof appContactSubmissionsSubmissionIdRoute
  appContactSubmissionsCreateRoute: typeof appContactSubmissionsCreateRoute
  appContactSubmissionsIndexRoute: typeof appContactSubmissionsIndexRoute
  appContactSubmissionsSubmissionIdEditRoute: typeof appContactSubmissionsSubmissionIdEditRoute
}

const appContactSubmissionsRouteRouteChildren: appContactSubmissionsRouteRouteChildren =
  {
    appContactSubmissionsSubmissionIdRoute:
      appContactSubmissionsSubmissionIdRoute,
    appContactSubmissionsCreateRoute: appContactSubmissionsCreateRoute,
    appContactSubmissionsIndexRoute: appContactSubmissionsIndexRoute,
    appContactSubmissionsSubmissionIdEditRoute:
      appContactSubmissionsSubmissionIdEditRoute,
  }

const appContactSubmissionsRouteRouteWithChildren =
  appContactSubmissionsRouteRoute._addFileChildren(
    appContactSubmissionsRouteRouteChildren,
  )

interface appInsecticidesRouteRouteChildren {
  appInsecticidesInsecticideIdRoute: typeof appInsecticidesInsecticideIdRoute
  appInsecticidesCreateRoute: typeof appInsecticidesCreateRoute
  appInsecticidesIndexRoute: typeof appInsecticidesIndexRoute
}

const appInsecticidesRouteRouteChildren: appInsecticidesRouteRouteChildren = {
  appInsecticidesInsecticideIdRoute: appInsecticidesInsecticideIdRoute,
  appInsecticidesCreateRoute: appInsecticidesCreateRoute,
  appInsecticidesIndexRoute: appInsecticidesIndexRoute,
}

const appInsecticidesRouteRouteWithChildren =
  appInsecticidesRouteRoute._addFileChildren(appInsecticidesRouteRouteChildren)

interface appMeetingsRouteRouteChildren {
  appMeetingsMeetingIdRoute: typeof appMeetingsMeetingIdRoute
  appMeetingsCreateRoute: typeof appMeetingsCreateRoute
  appMeetingsIndexRoute: typeof appMeetingsIndexRoute
}

const appMeetingsRouteRouteChildren: appMeetingsRouteRouteChildren = {
  appMeetingsMeetingIdRoute: appMeetingsMeetingIdRoute,
  appMeetingsCreateRoute: appMeetingsCreateRoute,
  appMeetingsIndexRoute: appMeetingsIndexRoute,
}

const appMeetingsRouteRouteWithChildren =
  appMeetingsRouteRoute._addFileChildren(appMeetingsRouteRouteChildren)

interface appNoticesRouteRouteChildren {
  appNoticesNoticeIdRoute: typeof appNoticesNoticeIdRoute
  appNoticesCreateRoute: typeof appNoticesCreateRoute
  appNoticesIndexRoute: typeof appNoticesIndexRoute
  appNoticesNoticeIdEditRoute: typeof appNoticesNoticeIdEditRoute
}

const appNoticesRouteRouteChildren: appNoticesRouteRouteChildren = {
  appNoticesNoticeIdRoute: appNoticesNoticeIdRoute,
  appNoticesCreateRoute: appNoticesCreateRoute,
  appNoticesIndexRoute: appNoticesIndexRoute,
  appNoticesNoticeIdEditRoute: appNoticesNoticeIdEditRoute,
}

const appNoticesRouteRouteWithChildren = appNoticesRouteRoute._addFileChildren(
  appNoticesRouteRouteChildren,
)

interface appServiceRequestsRouteRouteChildren {
  appServiceRequestsIndexRoute: typeof appServiceRequestsIndexRoute
  appServiceRequestsAdultMosquitoRequestIdRoute: typeof appServiceRequestsAdultMosquitoRequestIdRoute
  appServiceRequestsAdultMosquitoCreateRoute: typeof appServiceRequestsAdultMosquitoCreateRoute
  appServiceRequestsMosquitofishRequestIdRoute: typeof appServiceRequestsMosquitofishRequestIdRoute
  appServiceRequestsMosquitofishCreateRoute: typeof appServiceRequestsMosquitofishCreateRoute
  appServiceRequestsWaterManagementRequestIdRoute: typeof appServiceRequestsWaterManagementRequestIdRoute
  appServiceRequestsWaterManagementCreateRoute: typeof appServiceRequestsWaterManagementCreateRoute
  appServiceRequestsAdultMosquitoRequestIdEditRoute: typeof appServiceRequestsAdultMosquitoRequestIdEditRoute
  appServiceRequestsMosquitofishRequestIdEditRoute: typeof appServiceRequestsMosquitofishRequestIdEditRoute
  appServiceRequestsWaterManagementRequestIdEditRoute: typeof appServiceRequestsWaterManagementRequestIdEditRoute
}

const appServiceRequestsRouteRouteChildren: appServiceRequestsRouteRouteChildren =
  {
    appServiceRequestsIndexRoute: appServiceRequestsIndexRoute,
    appServiceRequestsAdultMosquitoRequestIdRoute:
      appServiceRequestsAdultMosquitoRequestIdRoute,
    appServiceRequestsAdultMosquitoCreateRoute:
      appServiceRequestsAdultMosquitoCreateRoute,
    appServiceRequestsMosquitofishRequestIdRoute:
      appServiceRequestsMosquitofishRequestIdRoute,
    appServiceRequestsMosquitofishCreateRoute:
      appServiceRequestsMosquitofishCreateRoute,
    appServiceRequestsWaterManagementRequestIdRoute:
      appServiceRequestsWaterManagementRequestIdRoute,
    appServiceRequestsWaterManagementCreateRoute:
      appServiceRequestsWaterManagementCreateRoute,
    appServiceRequestsAdultMosquitoRequestIdEditRoute:
      appServiceRequestsAdultMosquitoRequestIdEditRoute,
    appServiceRequestsMosquitofishRequestIdEditRoute:
      appServiceRequestsMosquitofishRequestIdEditRoute,
    appServiceRequestsWaterManagementRequestIdEditRoute:
      appServiceRequestsWaterManagementRequestIdEditRoute,
  }

const appServiceRequestsRouteRouteWithChildren =
  appServiceRequestsRouteRoute._addFileChildren(
    appServiceRequestsRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appContactSubmissionsRouteRoute: typeof appContactSubmissionsRouteRouteWithChildren
  appInsecticidesRouteRoute: typeof appInsecticidesRouteRouteWithChildren
  appMeetingsRouteRoute: typeof appMeetingsRouteRouteWithChildren
  appNoticesRouteRoute: typeof appNoticesRouteRouteWithChildren
  appServiceRequestsRouteRoute: typeof appServiceRequestsRouteRouteWithChildren
  appCategoriesRoute: typeof appCategoriesRoute
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appContactSubmissionsRouteRoute: appContactSubmissionsRouteRouteWithChildren,
  appInsecticidesRouteRoute: appInsecticidesRouteRouteWithChildren,
  appMeetingsRouteRoute: appMeetingsRouteRouteWithChildren,
  appNoticesRouteRoute: appNoticesRouteRouteWithChildren,
  appServiceRequestsRouteRoute: appServiceRequestsRouteRouteWithChildren,
  appCategoriesRoute: appCategoriesRoute,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
