/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appCategoriesRouteImport } from './routes/(app)/categories'
import { Route as appNoticesRouteRouteImport } from './routes/(app)/notices/route'
import { Route as appMeetingsRouteRouteImport } from './routes/(app)/meetings/route'
import { Route as appInsecticidesRouteRouteImport } from './routes/(app)/insecticides/route'
import { Route as appNoticesIndexRouteImport } from './routes/(app)/notices/index'
import { Route as appMeetingsIndexRouteImport } from './routes/(app)/meetings/index'
import { Route as appInsecticidesIndexRouteImport } from './routes/(app)/insecticides/index'
import { Route as appNoticesCreateRouteImport } from './routes/(app)/notices/create'
import { Route as appNoticesNoticeIdRouteImport } from './routes/(app)/notices/$noticeId'
import { Route as appMeetingsCreateRouteImport } from './routes/(app)/meetings/create'
import { Route as appMeetingsMeetingIdRouteImport } from './routes/(app)/meetings/$meetingId'
import { Route as appInsecticidesCreateRouteImport } from './routes/(app)/insecticides/create'
import { Route as appInsecticidesInsecticideIdRouteImport } from './routes/(app)/insecticides/$insecticideId'
import { Route as appNoticesNoticeIdEditRouteImport } from './routes/(app)/notices/$noticeId_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCategoriesRoute = appCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => appRouteRoute,
} as any)
const appNoticesRouteRoute = appNoticesRouteRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => appRouteRoute,
} as any)
const appMeetingsRouteRoute = appMeetingsRouteRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => appRouteRoute,
} as any)
const appInsecticidesRouteRoute = appInsecticidesRouteRouteImport.update({
  id: '/insecticides',
  path: '/insecticides',
  getParentRoute: () => appRouteRoute,
} as any)
const appNoticesIndexRoute = appNoticesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appMeetingsIndexRoute = appMeetingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appMeetingsRouteRoute,
} as any)
const appInsecticidesIndexRoute = appInsecticidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appInsecticidesRouteRoute,
} as any)
const appNoticesCreateRoute = appNoticesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appNoticesNoticeIdRoute = appNoticesNoticeIdRouteImport.update({
  id: '/$noticeId',
  path: '/$noticeId',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appMeetingsCreateRoute = appMeetingsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appMeetingsRouteRoute,
} as any)
const appMeetingsMeetingIdRoute = appMeetingsMeetingIdRouteImport.update({
  id: '/$meetingId',
  path: '/$meetingId',
  getParentRoute: () => appMeetingsRouteRoute,
} as any)
const appInsecticidesCreateRoute = appInsecticidesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appInsecticidesRouteRoute,
} as any)
const appInsecticidesInsecticideIdRoute =
  appInsecticidesInsecticideIdRouteImport.update({
    id: '/$insecticideId',
    path: '/$insecticideId',
    getParentRoute: () => appInsecticidesRouteRoute,
  } as any)
const appNoticesNoticeIdEditRoute = appNoticesNoticeIdEditRouteImport.update({
  id: '/$noticeId_/edit',
  path: '/$noticeId/edit',
  getParentRoute: () => appNoticesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/insecticides': typeof appInsecticidesRouteRouteWithChildren
  '/meetings': typeof appMeetingsRouteRouteWithChildren
  '/notices': typeof appNoticesRouteRouteWithChildren
  '/categories': typeof appCategoriesRoute
  '/': typeof appIndexRoute
  '/insecticides/$insecticideId': typeof appInsecticidesInsecticideIdRoute
  '/insecticides/create': typeof appInsecticidesCreateRoute
  '/meetings/$meetingId': typeof appMeetingsMeetingIdRoute
  '/meetings/create': typeof appMeetingsCreateRoute
  '/notices/$noticeId': typeof appNoticesNoticeIdRoute
  '/notices/create': typeof appNoticesCreateRoute
  '/insecticides/': typeof appInsecticidesIndexRoute
  '/meetings/': typeof appMeetingsIndexRoute
  '/notices/': typeof appNoticesIndexRoute
  '/notices/$noticeId/edit': typeof appNoticesNoticeIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/categories': typeof appCategoriesRoute
  '/': typeof appIndexRoute
  '/insecticides/$insecticideId': typeof appInsecticidesInsecticideIdRoute
  '/insecticides/create': typeof appInsecticidesCreateRoute
  '/meetings/$meetingId': typeof appMeetingsMeetingIdRoute
  '/meetings/create': typeof appMeetingsCreateRoute
  '/notices/$noticeId': typeof appNoticesNoticeIdRoute
  '/notices/create': typeof appNoticesCreateRoute
  '/insecticides': typeof appInsecticidesIndexRoute
  '/meetings': typeof appMeetingsIndexRoute
  '/notices': typeof appNoticesIndexRoute
  '/notices/$noticeId/edit': typeof appNoticesNoticeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(app)/insecticides': typeof appInsecticidesRouteRouteWithChildren
  '/(app)/meetings': typeof appMeetingsRouteRouteWithChildren
  '/(app)/notices': typeof appNoticesRouteRouteWithChildren
  '/(app)/categories': typeof appCategoriesRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/insecticides/$insecticideId': typeof appInsecticidesInsecticideIdRoute
  '/(app)/insecticides/create': typeof appInsecticidesCreateRoute
  '/(app)/meetings/$meetingId': typeof appMeetingsMeetingIdRoute
  '/(app)/meetings/create': typeof appMeetingsCreateRoute
  '/(app)/notices/$noticeId': typeof appNoticesNoticeIdRoute
  '/(app)/notices/create': typeof appNoticesCreateRoute
  '/(app)/insecticides/': typeof appInsecticidesIndexRoute
  '/(app)/meetings/': typeof appMeetingsIndexRoute
  '/(app)/notices/': typeof appNoticesIndexRoute
  '/(app)/notices/$noticeId_/edit': typeof appNoticesNoticeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/insecticides'
    | '/meetings'
    | '/notices'
    | '/categories'
    | '/'
    | '/insecticides/$insecticideId'
    | '/insecticides/create'
    | '/meetings/$meetingId'
    | '/meetings/create'
    | '/notices/$noticeId'
    | '/notices/create'
    | '/insecticides/'
    | '/meetings/'
    | '/notices/'
    | '/notices/$noticeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/categories'
    | '/'
    | '/insecticides/$insecticideId'
    | '/insecticides/create'
    | '/meetings/$meetingId'
    | '/meetings/create'
    | '/notices/$noticeId'
    | '/notices/create'
    | '/insecticides'
    | '/meetings'
    | '/notices'
    | '/notices/$noticeId/edit'
  id:
    | '__root__'
    | '/(app)'
    | '/login'
    | '/(app)/insecticides'
    | '/(app)/meetings'
    | '/(app)/notices'
    | '/(app)/categories'
    | '/(app)/'
    | '/(app)/insecticides/$insecticideId'
    | '/(app)/insecticides/create'
    | '/(app)/meetings/$meetingId'
    | '/(app)/meetings/create'
    | '/(app)/notices/$noticeId'
    | '/(app)/notices/create'
    | '/(app)/insecticides/'
    | '/(app)/meetings/'
    | '/(app)/notices/'
    | '/(app)/notices/$noticeId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/categories': {
      id: '/(app)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof appCategoriesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/notices': {
      id: '/(app)/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof appNoticesRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/meetings': {
      id: '/(app)/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof appMeetingsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/insecticides': {
      id: '/(app)/insecticides'
      path: '/insecticides'
      fullPath: '/insecticides'
      preLoaderRoute: typeof appInsecticidesRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/notices/': {
      id: '/(app)/notices/'
      path: '/'
      fullPath: '/notices/'
      preLoaderRoute: typeof appNoticesIndexRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/meetings/': {
      id: '/(app)/meetings/'
      path: '/'
      fullPath: '/meetings/'
      preLoaderRoute: typeof appMeetingsIndexRouteImport
      parentRoute: typeof appMeetingsRouteRoute
    }
    '/(app)/insecticides/': {
      id: '/(app)/insecticides/'
      path: '/'
      fullPath: '/insecticides/'
      preLoaderRoute: typeof appInsecticidesIndexRouteImport
      parentRoute: typeof appInsecticidesRouteRoute
    }
    '/(app)/notices/create': {
      id: '/(app)/notices/create'
      path: '/create'
      fullPath: '/notices/create'
      preLoaderRoute: typeof appNoticesCreateRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/notices/$noticeId': {
      id: '/(app)/notices/$noticeId'
      path: '/$noticeId'
      fullPath: '/notices/$noticeId'
      preLoaderRoute: typeof appNoticesNoticeIdRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/meetings/create': {
      id: '/(app)/meetings/create'
      path: '/create'
      fullPath: '/meetings/create'
      preLoaderRoute: typeof appMeetingsCreateRouteImport
      parentRoute: typeof appMeetingsRouteRoute
    }
    '/(app)/meetings/$meetingId': {
      id: '/(app)/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof appMeetingsMeetingIdRouteImport
      parentRoute: typeof appMeetingsRouteRoute
    }
    '/(app)/insecticides/create': {
      id: '/(app)/insecticides/create'
      path: '/create'
      fullPath: '/insecticides/create'
      preLoaderRoute: typeof appInsecticidesCreateRouteImport
      parentRoute: typeof appInsecticidesRouteRoute
    }
    '/(app)/insecticides/$insecticideId': {
      id: '/(app)/insecticides/$insecticideId'
      path: '/$insecticideId'
      fullPath: '/insecticides/$insecticideId'
      preLoaderRoute: typeof appInsecticidesInsecticideIdRouteImport
      parentRoute: typeof appInsecticidesRouteRoute
    }
    '/(app)/notices/$noticeId_/edit': {
      id: '/(app)/notices/$noticeId_/edit'
      path: '/$noticeId/edit'
      fullPath: '/notices/$noticeId/edit'
      preLoaderRoute: typeof appNoticesNoticeIdEditRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
  }
}

interface appInsecticidesRouteRouteChildren {
  appInsecticidesInsecticideIdRoute: typeof appInsecticidesInsecticideIdRoute
  appInsecticidesCreateRoute: typeof appInsecticidesCreateRoute
  appInsecticidesIndexRoute: typeof appInsecticidesIndexRoute
}

const appInsecticidesRouteRouteChildren: appInsecticidesRouteRouteChildren = {
  appInsecticidesInsecticideIdRoute: appInsecticidesInsecticideIdRoute,
  appInsecticidesCreateRoute: appInsecticidesCreateRoute,
  appInsecticidesIndexRoute: appInsecticidesIndexRoute,
}

const appInsecticidesRouteRouteWithChildren =
  appInsecticidesRouteRoute._addFileChildren(appInsecticidesRouteRouteChildren)

interface appMeetingsRouteRouteChildren {
  appMeetingsMeetingIdRoute: typeof appMeetingsMeetingIdRoute
  appMeetingsCreateRoute: typeof appMeetingsCreateRoute
  appMeetingsIndexRoute: typeof appMeetingsIndexRoute
}

const appMeetingsRouteRouteChildren: appMeetingsRouteRouteChildren = {
  appMeetingsMeetingIdRoute: appMeetingsMeetingIdRoute,
  appMeetingsCreateRoute: appMeetingsCreateRoute,
  appMeetingsIndexRoute: appMeetingsIndexRoute,
}

const appMeetingsRouteRouteWithChildren =
  appMeetingsRouteRoute._addFileChildren(appMeetingsRouteRouteChildren)

interface appNoticesRouteRouteChildren {
  appNoticesNoticeIdRoute: typeof appNoticesNoticeIdRoute
  appNoticesCreateRoute: typeof appNoticesCreateRoute
  appNoticesIndexRoute: typeof appNoticesIndexRoute
  appNoticesNoticeIdEditRoute: typeof appNoticesNoticeIdEditRoute
}

const appNoticesRouteRouteChildren: appNoticesRouteRouteChildren = {
  appNoticesNoticeIdRoute: appNoticesNoticeIdRoute,
  appNoticesCreateRoute: appNoticesCreateRoute,
  appNoticesIndexRoute: appNoticesIndexRoute,
  appNoticesNoticeIdEditRoute: appNoticesNoticeIdEditRoute,
}

const appNoticesRouteRouteWithChildren = appNoticesRouteRoute._addFileChildren(
  appNoticesRouteRouteChildren,
)

interface appRouteRouteChildren {
  appInsecticidesRouteRoute: typeof appInsecticidesRouteRouteWithChildren
  appMeetingsRouteRoute: typeof appMeetingsRouteRouteWithChildren
  appNoticesRouteRoute: typeof appNoticesRouteRouteWithChildren
  appCategoriesRoute: typeof appCategoriesRoute
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appInsecticidesRouteRoute: appInsecticidesRouteRouteWithChildren,
  appMeetingsRouteRoute: appMeetingsRouteRouteWithChildren,
  appNoticesRouteRoute: appNoticesRouteRouteWithChildren,
  appCategoriesRoute: appCategoriesRoute,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
