/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appDocumentCategoriesRouteImport } from './routes/(app)/document-categories'
import { Route as appCategoriesRouteImport } from './routes/(app)/categories'
import { Route as appSprayScheduleRouteRouteImport } from './routes/(app)/spray-schedule/route'
import { Route as appPublicRequestsRouteRouteImport } from './routes/(app)/public-requests/route'
import { Route as appNoticesRouteRouteImport } from './routes/(app)/notices/route'
import { Route as appMeetingsRouteRouteImport } from './routes/(app)/meetings/route'
import { Route as appInsecticidesRouteRouteImport } from './routes/(app)/insecticides/route'
import { Route as appDocumentsRouteRouteImport } from './routes/(app)/documents/route'
import { Route as appWeeklyActivityIndexRouteImport } from './routes/(app)/weekly-activity/index'
import { Route as appSprayScheduleIndexRouteImport } from './routes/(app)/spray-schedule/index'
import { Route as appPublicRequestsIndexRouteImport } from './routes/(app)/public-requests/index'
import { Route as appNoticesIndexRouteImport } from './routes/(app)/notices/index'
import { Route as appMeetingsIndexRouteImport } from './routes/(app)/meetings/index'
import { Route as appInsecticidesIndexRouteImport } from './routes/(app)/insecticides/index'
import { Route as appDocumentsIndexRouteImport } from './routes/(app)/documents/index'
import { Route as appSprayScheduleCreateRouteImport } from './routes/(app)/spray-schedule/create'
import { Route as appSprayScheduleSprayScheduleIdRouteImport } from './routes/(app)/spray-schedule/$sprayScheduleId'
import { Route as appPublicRequestsRequestIdRouteImport } from './routes/(app)/public-requests/$requestId'
import { Route as appNoticesCreateRouteImport } from './routes/(app)/notices/create'
import { Route as appNoticesNoticeIdRouteImport } from './routes/(app)/notices/$noticeId'
import { Route as appMeetingsCreateRouteImport } from './routes/(app)/meetings/create'
import { Route as appMeetingsMeetingIdRouteImport } from './routes/(app)/meetings/$meetingId'
import { Route as appInsecticidesCreateRouteImport } from './routes/(app)/insecticides/create'
import { Route as appInsecticidesInsecticideIdRouteImport } from './routes/(app)/insecticides/$insecticideId'
import { Route as appDocumentsCreateRouteImport } from './routes/(app)/documents/create'
import { Route as appDocumentsDocumentIdRouteImport } from './routes/(app)/documents/$documentId'
import { Route as appNoticesNoticeIdEditRouteImport } from './routes/(app)/notices/$noticeId_.edit'
import { Route as appDocumentsDocumentIdEditRouteImport } from './routes/(app)/documents/$documentId_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appDocumentCategoriesRoute = appDocumentCategoriesRouteImport.update({
  id: '/document-categories',
  path: '/document-categories',
  getParentRoute: () => appRouteRoute,
} as any)
const appCategoriesRoute = appCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => appRouteRoute,
} as any)
const appSprayScheduleRouteRoute = appSprayScheduleRouteRouteImport.update({
  id: '/spray-schedule',
  path: '/spray-schedule',
  getParentRoute: () => appRouteRoute,
} as any)
const appPublicRequestsRouteRoute = appPublicRequestsRouteRouteImport.update({
  id: '/public-requests',
  path: '/public-requests',
  getParentRoute: () => appRouteRoute,
} as any)
const appNoticesRouteRoute = appNoticesRouteRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => appRouteRoute,
} as any)
const appMeetingsRouteRoute = appMeetingsRouteRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => appRouteRoute,
} as any)
const appInsecticidesRouteRoute = appInsecticidesRouteRouteImport.update({
  id: '/insecticides',
  path: '/insecticides',
  getParentRoute: () => appRouteRoute,
} as any)
const appDocumentsRouteRoute = appDocumentsRouteRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => appRouteRoute,
} as any)
const appWeeklyActivityIndexRoute = appWeeklyActivityIndexRouteImport.update({
  id: '/weekly-activity/',
  path: '/weekly-activity/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSprayScheduleIndexRoute = appSprayScheduleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appSprayScheduleRouteRoute,
} as any)
const appPublicRequestsIndexRoute = appPublicRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appPublicRequestsRouteRoute,
} as any)
const appNoticesIndexRoute = appNoticesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appMeetingsIndexRoute = appMeetingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appMeetingsRouteRoute,
} as any)
const appInsecticidesIndexRoute = appInsecticidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appInsecticidesRouteRoute,
} as any)
const appDocumentsIndexRoute = appDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDocumentsRouteRoute,
} as any)
const appSprayScheduleCreateRoute = appSprayScheduleCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appSprayScheduleRouteRoute,
} as any)
const appSprayScheduleSprayScheduleIdRoute =
  appSprayScheduleSprayScheduleIdRouteImport.update({
    id: '/$sprayScheduleId',
    path: '/$sprayScheduleId',
    getParentRoute: () => appSprayScheduleRouteRoute,
  } as any)
const appPublicRequestsRequestIdRoute =
  appPublicRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => appPublicRequestsRouteRoute,
  } as any)
const appNoticesCreateRoute = appNoticesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appNoticesNoticeIdRoute = appNoticesNoticeIdRouteImport.update({
  id: '/$noticeId',
  path: '/$noticeId',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appMeetingsCreateRoute = appMeetingsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appMeetingsRouteRoute,
} as any)
const appMeetingsMeetingIdRoute = appMeetingsMeetingIdRouteImport.update({
  id: '/$meetingId',
  path: '/$meetingId',
  getParentRoute: () => appMeetingsRouteRoute,
} as any)
const appInsecticidesCreateRoute = appInsecticidesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appInsecticidesRouteRoute,
} as any)
const appInsecticidesInsecticideIdRoute =
  appInsecticidesInsecticideIdRouteImport.update({
    id: '/$insecticideId',
    path: '/$insecticideId',
    getParentRoute: () => appInsecticidesRouteRoute,
  } as any)
const appDocumentsCreateRoute = appDocumentsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appDocumentsRouteRoute,
} as any)
const appDocumentsDocumentIdRoute = appDocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => appDocumentsRouteRoute,
} as any)
const appNoticesNoticeIdEditRoute = appNoticesNoticeIdEditRouteImport.update({
  id: '/$noticeId_/edit',
  path: '/$noticeId/edit',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appDocumentsDocumentIdEditRoute =
  appDocumentsDocumentIdEditRouteImport.update({
    id: '/$documentId_/edit',
    path: '/$documentId/edit',
    getParentRoute: () => appDocumentsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/documents': typeof appDocumentsRouteRouteWithChildren
  '/insecticides': typeof appInsecticidesRouteRouteWithChildren
  '/meetings': typeof appMeetingsRouteRouteWithChildren
  '/notices': typeof appNoticesRouteRouteWithChildren
  '/public-requests': typeof appPublicRequestsRouteRouteWithChildren
  '/spray-schedule': typeof appSprayScheduleRouteRouteWithChildren
  '/categories': typeof appCategoriesRoute
  '/document-categories': typeof appDocumentCategoriesRoute
  '/': typeof appIndexRoute
  '/documents/$documentId': typeof appDocumentsDocumentIdRoute
  '/documents/create': typeof appDocumentsCreateRoute
  '/insecticides/$insecticideId': typeof appInsecticidesInsecticideIdRoute
  '/insecticides/create': typeof appInsecticidesCreateRoute
  '/meetings/$meetingId': typeof appMeetingsMeetingIdRoute
  '/meetings/create': typeof appMeetingsCreateRoute
  '/notices/$noticeId': typeof appNoticesNoticeIdRoute
  '/notices/create': typeof appNoticesCreateRoute
  '/public-requests/$requestId': typeof appPublicRequestsRequestIdRoute
  '/spray-schedule/$sprayScheduleId': typeof appSprayScheduleSprayScheduleIdRoute
  '/spray-schedule/create': typeof appSprayScheduleCreateRoute
  '/documents/': typeof appDocumentsIndexRoute
  '/insecticides/': typeof appInsecticidesIndexRoute
  '/meetings/': typeof appMeetingsIndexRoute
  '/notices/': typeof appNoticesIndexRoute
  '/public-requests/': typeof appPublicRequestsIndexRoute
  '/spray-schedule/': typeof appSprayScheduleIndexRoute
  '/weekly-activity/': typeof appWeeklyActivityIndexRoute
  '/documents/$documentId/edit': typeof appDocumentsDocumentIdEditRoute
  '/notices/$noticeId/edit': typeof appNoticesNoticeIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/categories': typeof appCategoriesRoute
  '/document-categories': typeof appDocumentCategoriesRoute
  '/': typeof appIndexRoute
  '/documents/$documentId': typeof appDocumentsDocumentIdRoute
  '/documents/create': typeof appDocumentsCreateRoute
  '/insecticides/$insecticideId': typeof appInsecticidesInsecticideIdRoute
  '/insecticides/create': typeof appInsecticidesCreateRoute
  '/meetings/$meetingId': typeof appMeetingsMeetingIdRoute
  '/meetings/create': typeof appMeetingsCreateRoute
  '/notices/$noticeId': typeof appNoticesNoticeIdRoute
  '/notices/create': typeof appNoticesCreateRoute
  '/public-requests/$requestId': typeof appPublicRequestsRequestIdRoute
  '/spray-schedule/$sprayScheduleId': typeof appSprayScheduleSprayScheduleIdRoute
  '/spray-schedule/create': typeof appSprayScheduleCreateRoute
  '/documents': typeof appDocumentsIndexRoute
  '/insecticides': typeof appInsecticidesIndexRoute
  '/meetings': typeof appMeetingsIndexRoute
  '/notices': typeof appNoticesIndexRoute
  '/public-requests': typeof appPublicRequestsIndexRoute
  '/spray-schedule': typeof appSprayScheduleIndexRoute
  '/weekly-activity': typeof appWeeklyActivityIndexRoute
  '/documents/$documentId/edit': typeof appDocumentsDocumentIdEditRoute
  '/notices/$noticeId/edit': typeof appNoticesNoticeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(app)/documents': typeof appDocumentsRouteRouteWithChildren
  '/(app)/insecticides': typeof appInsecticidesRouteRouteWithChildren
  '/(app)/meetings': typeof appMeetingsRouteRouteWithChildren
  '/(app)/notices': typeof appNoticesRouteRouteWithChildren
  '/(app)/public-requests': typeof appPublicRequestsRouteRouteWithChildren
  '/(app)/spray-schedule': typeof appSprayScheduleRouteRouteWithChildren
  '/(app)/categories': typeof appCategoriesRoute
  '/(app)/document-categories': typeof appDocumentCategoriesRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/documents/$documentId': typeof appDocumentsDocumentIdRoute
  '/(app)/documents/create': typeof appDocumentsCreateRoute
  '/(app)/insecticides/$insecticideId': typeof appInsecticidesInsecticideIdRoute
  '/(app)/insecticides/create': typeof appInsecticidesCreateRoute
  '/(app)/meetings/$meetingId': typeof appMeetingsMeetingIdRoute
  '/(app)/meetings/create': typeof appMeetingsCreateRoute
  '/(app)/notices/$noticeId': typeof appNoticesNoticeIdRoute
  '/(app)/notices/create': typeof appNoticesCreateRoute
  '/(app)/public-requests/$requestId': typeof appPublicRequestsRequestIdRoute
  '/(app)/spray-schedule/$sprayScheduleId': typeof appSprayScheduleSprayScheduleIdRoute
  '/(app)/spray-schedule/create': typeof appSprayScheduleCreateRoute
  '/(app)/documents/': typeof appDocumentsIndexRoute
  '/(app)/insecticides/': typeof appInsecticidesIndexRoute
  '/(app)/meetings/': typeof appMeetingsIndexRoute
  '/(app)/notices/': typeof appNoticesIndexRoute
  '/(app)/public-requests/': typeof appPublicRequestsIndexRoute
  '/(app)/spray-schedule/': typeof appSprayScheduleIndexRoute
  '/(app)/weekly-activity/': typeof appWeeklyActivityIndexRoute
  '/(app)/documents/$documentId_/edit': typeof appDocumentsDocumentIdEditRoute
  '/(app)/notices/$noticeId_/edit': typeof appNoticesNoticeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/documents'
    | '/insecticides'
    | '/meetings'
    | '/notices'
    | '/public-requests'
    | '/spray-schedule'
    | '/categories'
    | '/document-categories'
    | '/'
    | '/documents/$documentId'
    | '/documents/create'
    | '/insecticides/$insecticideId'
    | '/insecticides/create'
    | '/meetings/$meetingId'
    | '/meetings/create'
    | '/notices/$noticeId'
    | '/notices/create'
    | '/public-requests/$requestId'
    | '/spray-schedule/$sprayScheduleId'
    | '/spray-schedule/create'
    | '/documents/'
    | '/insecticides/'
    | '/meetings/'
    | '/notices/'
    | '/public-requests/'
    | '/spray-schedule/'
    | '/weekly-activity/'
    | '/documents/$documentId/edit'
    | '/notices/$noticeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/categories'
    | '/document-categories'
    | '/'
    | '/documents/$documentId'
    | '/documents/create'
    | '/insecticides/$insecticideId'
    | '/insecticides/create'
    | '/meetings/$meetingId'
    | '/meetings/create'
    | '/notices/$noticeId'
    | '/notices/create'
    | '/public-requests/$requestId'
    | '/spray-schedule/$sprayScheduleId'
    | '/spray-schedule/create'
    | '/documents'
    | '/insecticides'
    | '/meetings'
    | '/notices'
    | '/public-requests'
    | '/spray-schedule'
    | '/weekly-activity'
    | '/documents/$documentId/edit'
    | '/notices/$noticeId/edit'
  id:
    | '__root__'
    | '/(app)'
    | '/login'
    | '/(app)/documents'
    | '/(app)/insecticides'
    | '/(app)/meetings'
    | '/(app)/notices'
    | '/(app)/public-requests'
    | '/(app)/spray-schedule'
    | '/(app)/categories'
    | '/(app)/document-categories'
    | '/(app)/'
    | '/(app)/documents/$documentId'
    | '/(app)/documents/create'
    | '/(app)/insecticides/$insecticideId'
    | '/(app)/insecticides/create'
    | '/(app)/meetings/$meetingId'
    | '/(app)/meetings/create'
    | '/(app)/notices/$noticeId'
    | '/(app)/notices/create'
    | '/(app)/public-requests/$requestId'
    | '/(app)/spray-schedule/$sprayScheduleId'
    | '/(app)/spray-schedule/create'
    | '/(app)/documents/'
    | '/(app)/insecticides/'
    | '/(app)/meetings/'
    | '/(app)/notices/'
    | '/(app)/public-requests/'
    | '/(app)/spray-schedule/'
    | '/(app)/weekly-activity/'
    | '/(app)/documents/$documentId_/edit'
    | '/(app)/notices/$noticeId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/document-categories': {
      id: '/(app)/document-categories'
      path: '/document-categories'
      fullPath: '/document-categories'
      preLoaderRoute: typeof appDocumentCategoriesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/categories': {
      id: '/(app)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof appCategoriesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/spray-schedule': {
      id: '/(app)/spray-schedule'
      path: '/spray-schedule'
      fullPath: '/spray-schedule'
      preLoaderRoute: typeof appSprayScheduleRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/public-requests': {
      id: '/(app)/public-requests'
      path: '/public-requests'
      fullPath: '/public-requests'
      preLoaderRoute: typeof appPublicRequestsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/notices': {
      id: '/(app)/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof appNoticesRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/meetings': {
      id: '/(app)/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof appMeetingsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/insecticides': {
      id: '/(app)/insecticides'
      path: '/insecticides'
      fullPath: '/insecticides'
      preLoaderRoute: typeof appInsecticidesRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/documents': {
      id: '/(app)/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof appDocumentsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/weekly-activity/': {
      id: '/(app)/weekly-activity/'
      path: '/weekly-activity'
      fullPath: '/weekly-activity/'
      preLoaderRoute: typeof appWeeklyActivityIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/spray-schedule/': {
      id: '/(app)/spray-schedule/'
      path: '/'
      fullPath: '/spray-schedule/'
      preLoaderRoute: typeof appSprayScheduleIndexRouteImport
      parentRoute: typeof appSprayScheduleRouteRoute
    }
    '/(app)/public-requests/': {
      id: '/(app)/public-requests/'
      path: '/'
      fullPath: '/public-requests/'
      preLoaderRoute: typeof appPublicRequestsIndexRouteImport
      parentRoute: typeof appPublicRequestsRouteRoute
    }
    '/(app)/notices/': {
      id: '/(app)/notices/'
      path: '/'
      fullPath: '/notices/'
      preLoaderRoute: typeof appNoticesIndexRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/meetings/': {
      id: '/(app)/meetings/'
      path: '/'
      fullPath: '/meetings/'
      preLoaderRoute: typeof appMeetingsIndexRouteImport
      parentRoute: typeof appMeetingsRouteRoute
    }
    '/(app)/insecticides/': {
      id: '/(app)/insecticides/'
      path: '/'
      fullPath: '/insecticides/'
      preLoaderRoute: typeof appInsecticidesIndexRouteImport
      parentRoute: typeof appInsecticidesRouteRoute
    }
    '/(app)/documents/': {
      id: '/(app)/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof appDocumentsIndexRouteImport
      parentRoute: typeof appDocumentsRouteRoute
    }
    '/(app)/spray-schedule/create': {
      id: '/(app)/spray-schedule/create'
      path: '/create'
      fullPath: '/spray-schedule/create'
      preLoaderRoute: typeof appSprayScheduleCreateRouteImport
      parentRoute: typeof appSprayScheduleRouteRoute
    }
    '/(app)/spray-schedule/$sprayScheduleId': {
      id: '/(app)/spray-schedule/$sprayScheduleId'
      path: '/$sprayScheduleId'
      fullPath: '/spray-schedule/$sprayScheduleId'
      preLoaderRoute: typeof appSprayScheduleSprayScheduleIdRouteImport
      parentRoute: typeof appSprayScheduleRouteRoute
    }
    '/(app)/public-requests/$requestId': {
      id: '/(app)/public-requests/$requestId'
      path: '/$requestId'
      fullPath: '/public-requests/$requestId'
      preLoaderRoute: typeof appPublicRequestsRequestIdRouteImport
      parentRoute: typeof appPublicRequestsRouteRoute
    }
    '/(app)/notices/create': {
      id: '/(app)/notices/create'
      path: '/create'
      fullPath: '/notices/create'
      preLoaderRoute: typeof appNoticesCreateRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/notices/$noticeId': {
      id: '/(app)/notices/$noticeId'
      path: '/$noticeId'
      fullPath: '/notices/$noticeId'
      preLoaderRoute: typeof appNoticesNoticeIdRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/meetings/create': {
      id: '/(app)/meetings/create'
      path: '/create'
      fullPath: '/meetings/create'
      preLoaderRoute: typeof appMeetingsCreateRouteImport
      parentRoute: typeof appMeetingsRouteRoute
    }
    '/(app)/meetings/$meetingId': {
      id: '/(app)/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof appMeetingsMeetingIdRouteImport
      parentRoute: typeof appMeetingsRouteRoute
    }
    '/(app)/insecticides/create': {
      id: '/(app)/insecticides/create'
      path: '/create'
      fullPath: '/insecticides/create'
      preLoaderRoute: typeof appInsecticidesCreateRouteImport
      parentRoute: typeof appInsecticidesRouteRoute
    }
    '/(app)/insecticides/$insecticideId': {
      id: '/(app)/insecticides/$insecticideId'
      path: '/$insecticideId'
      fullPath: '/insecticides/$insecticideId'
      preLoaderRoute: typeof appInsecticidesInsecticideIdRouteImport
      parentRoute: typeof appInsecticidesRouteRoute
    }
    '/(app)/documents/create': {
      id: '/(app)/documents/create'
      path: '/create'
      fullPath: '/documents/create'
      preLoaderRoute: typeof appDocumentsCreateRouteImport
      parentRoute: typeof appDocumentsRouteRoute
    }
    '/(app)/documents/$documentId': {
      id: '/(app)/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof appDocumentsDocumentIdRouteImport
      parentRoute: typeof appDocumentsRouteRoute
    }
    '/(app)/notices/$noticeId_/edit': {
      id: '/(app)/notices/$noticeId_/edit'
      path: '/$noticeId/edit'
      fullPath: '/notices/$noticeId/edit'
      preLoaderRoute: typeof appNoticesNoticeIdEditRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/documents/$documentId_/edit': {
      id: '/(app)/documents/$documentId_/edit'
      path: '/$documentId/edit'
      fullPath: '/documents/$documentId/edit'
      preLoaderRoute: typeof appDocumentsDocumentIdEditRouteImport
      parentRoute: typeof appDocumentsRouteRoute
    }
  }
}

interface appDocumentsRouteRouteChildren {
  appDocumentsDocumentIdRoute: typeof appDocumentsDocumentIdRoute
  appDocumentsCreateRoute: typeof appDocumentsCreateRoute
  appDocumentsIndexRoute: typeof appDocumentsIndexRoute
  appDocumentsDocumentIdEditRoute: typeof appDocumentsDocumentIdEditRoute
}

const appDocumentsRouteRouteChildren: appDocumentsRouteRouteChildren = {
  appDocumentsDocumentIdRoute: appDocumentsDocumentIdRoute,
  appDocumentsCreateRoute: appDocumentsCreateRoute,
  appDocumentsIndexRoute: appDocumentsIndexRoute,
  appDocumentsDocumentIdEditRoute: appDocumentsDocumentIdEditRoute,
}

const appDocumentsRouteRouteWithChildren =
  appDocumentsRouteRoute._addFileChildren(appDocumentsRouteRouteChildren)

interface appInsecticidesRouteRouteChildren {
  appInsecticidesInsecticideIdRoute: typeof appInsecticidesInsecticideIdRoute
  appInsecticidesCreateRoute: typeof appInsecticidesCreateRoute
  appInsecticidesIndexRoute: typeof appInsecticidesIndexRoute
}

const appInsecticidesRouteRouteChildren: appInsecticidesRouteRouteChildren = {
  appInsecticidesInsecticideIdRoute: appInsecticidesInsecticideIdRoute,
  appInsecticidesCreateRoute: appInsecticidesCreateRoute,
  appInsecticidesIndexRoute: appInsecticidesIndexRoute,
}

const appInsecticidesRouteRouteWithChildren =
  appInsecticidesRouteRoute._addFileChildren(appInsecticidesRouteRouteChildren)

interface appMeetingsRouteRouteChildren {
  appMeetingsMeetingIdRoute: typeof appMeetingsMeetingIdRoute
  appMeetingsCreateRoute: typeof appMeetingsCreateRoute
  appMeetingsIndexRoute: typeof appMeetingsIndexRoute
}

const appMeetingsRouteRouteChildren: appMeetingsRouteRouteChildren = {
  appMeetingsMeetingIdRoute: appMeetingsMeetingIdRoute,
  appMeetingsCreateRoute: appMeetingsCreateRoute,
  appMeetingsIndexRoute: appMeetingsIndexRoute,
}

const appMeetingsRouteRouteWithChildren =
  appMeetingsRouteRoute._addFileChildren(appMeetingsRouteRouteChildren)

interface appNoticesRouteRouteChildren {
  appNoticesNoticeIdRoute: typeof appNoticesNoticeIdRoute
  appNoticesCreateRoute: typeof appNoticesCreateRoute
  appNoticesIndexRoute: typeof appNoticesIndexRoute
  appNoticesNoticeIdEditRoute: typeof appNoticesNoticeIdEditRoute
}

const appNoticesRouteRouteChildren: appNoticesRouteRouteChildren = {
  appNoticesNoticeIdRoute: appNoticesNoticeIdRoute,
  appNoticesCreateRoute: appNoticesCreateRoute,
  appNoticesIndexRoute: appNoticesIndexRoute,
  appNoticesNoticeIdEditRoute: appNoticesNoticeIdEditRoute,
}

const appNoticesRouteRouteWithChildren = appNoticesRouteRoute._addFileChildren(
  appNoticesRouteRouteChildren,
)

interface appPublicRequestsRouteRouteChildren {
  appPublicRequestsRequestIdRoute: typeof appPublicRequestsRequestIdRoute
  appPublicRequestsIndexRoute: typeof appPublicRequestsIndexRoute
}

const appPublicRequestsRouteRouteChildren: appPublicRequestsRouteRouteChildren =
  {
    appPublicRequestsRequestIdRoute: appPublicRequestsRequestIdRoute,
    appPublicRequestsIndexRoute: appPublicRequestsIndexRoute,
  }

const appPublicRequestsRouteRouteWithChildren =
  appPublicRequestsRouteRoute._addFileChildren(
    appPublicRequestsRouteRouteChildren,
  )

interface appSprayScheduleRouteRouteChildren {
  appSprayScheduleSprayScheduleIdRoute: typeof appSprayScheduleSprayScheduleIdRoute
  appSprayScheduleCreateRoute: typeof appSprayScheduleCreateRoute
  appSprayScheduleIndexRoute: typeof appSprayScheduleIndexRoute
}

const appSprayScheduleRouteRouteChildren: appSprayScheduleRouteRouteChildren = {
  appSprayScheduleSprayScheduleIdRoute: appSprayScheduleSprayScheduleIdRoute,
  appSprayScheduleCreateRoute: appSprayScheduleCreateRoute,
  appSprayScheduleIndexRoute: appSprayScheduleIndexRoute,
}

const appSprayScheduleRouteRouteWithChildren =
  appSprayScheduleRouteRoute._addFileChildren(
    appSprayScheduleRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appDocumentsRouteRoute: typeof appDocumentsRouteRouteWithChildren
  appInsecticidesRouteRoute: typeof appInsecticidesRouteRouteWithChildren
  appMeetingsRouteRoute: typeof appMeetingsRouteRouteWithChildren
  appNoticesRouteRoute: typeof appNoticesRouteRouteWithChildren
  appPublicRequestsRouteRoute: typeof appPublicRequestsRouteRouteWithChildren
  appSprayScheduleRouteRoute: typeof appSprayScheduleRouteRouteWithChildren
  appCategoriesRoute: typeof appCategoriesRoute
  appDocumentCategoriesRoute: typeof appDocumentCategoriesRoute
  appIndexRoute: typeof appIndexRoute
  appWeeklyActivityIndexRoute: typeof appWeeklyActivityIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDocumentsRouteRoute: appDocumentsRouteRouteWithChildren,
  appInsecticidesRouteRoute: appInsecticidesRouteRouteWithChildren,
  appMeetingsRouteRoute: appMeetingsRouteRouteWithChildren,
  appNoticesRouteRoute: appNoticesRouteRouteWithChildren,
  appPublicRequestsRouteRoute: appPublicRequestsRouteRouteWithChildren,
  appSprayScheduleRouteRoute: appSprayScheduleRouteRouteWithChildren,
  appCategoriesRoute: appCategoriesRoute,
  appDocumentCategoriesRoute: appDocumentCategoriesRoute,
  appIndexRoute: appIndexRoute,
  appWeeklyActivityIndexRoute: appWeeklyActivityIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
