/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appSprayScheduleRouteRouteImport } from './routes/(app)/spray-schedule/route'
import { Route as appPublicRequestsRouteRouteImport } from './routes/(app)/public-requests/route'
import { Route as appNoticesRouteRouteImport } from './routes/(app)/notices/route'
import { Route as appMeetingsRouteRouteImport } from './routes/(app)/meetings/route'
import { Route as appJobPostingsRouteRouteImport } from './routes/(app)/job-postings/route'
import { Route as appInsecticidesRouteRouteImport } from './routes/(app)/insecticides/route'
import { Route as appDocumentsRouteRouteImport } from './routes/(app)/documents/route'
import { Route as appDocumentCategoriesRouteRouteImport } from './routes/(app)/document-categories/route'
import { Route as appCategoriesRouteRouteImport } from './routes/(app)/categories/route'
import { Route as appWeeklyActivityIndexRouteImport } from './routes/(app)/weekly-activity/index'
import { Route as appSprayScheduleIndexRouteImport } from './routes/(app)/spray-schedule/index'
import { Route as appPublicRequestsIndexRouteImport } from './routes/(app)/public-requests/index'
import { Route as appNoticesIndexRouteImport } from './routes/(app)/notices/index'
import { Route as appMeetingsIndexRouteImport } from './routes/(app)/meetings/index'
import { Route as appJobPostingsIndexRouteImport } from './routes/(app)/job-postings/index'
import { Route as appInsecticidesIndexRouteImport } from './routes/(app)/insecticides/index'
import { Route as appDocumentsIndexRouteImport } from './routes/(app)/documents/index'
import { Route as appDocumentCategoriesIndexRouteImport } from './routes/(app)/document-categories/index'
import { Route as appCategoriesIndexRouteImport } from './routes/(app)/categories/index'
import { Route as appSprayScheduleCreateRouteImport } from './routes/(app)/spray-schedule/create'
import { Route as appSprayScheduleSprayScheduleIdRouteImport } from './routes/(app)/spray-schedule/$sprayScheduleId'
import { Route as appPublicRequestsRequestIdRouteImport } from './routes/(app)/public-requests/$requestId'
import { Route as appNoticesCreateRouteImport } from './routes/(app)/notices/create'
import { Route as appNoticesNoticeIdRouteImport } from './routes/(app)/notices/$noticeId'
import { Route as appMeetingsCreateRouteImport } from './routes/(app)/meetings/create'
import { Route as appMeetingsMeetingIdRouteImport } from './routes/(app)/meetings/$meetingId'
import { Route as appJobPostingsCreateRouteImport } from './routes/(app)/job-postings/create'
import { Route as appJobPostingsPostingIdRouteImport } from './routes/(app)/job-postings/$postingId'
import { Route as appInsecticidesCreateRouteImport } from './routes/(app)/insecticides/create'
import { Route as appInsecticidesInsecticideIdRouteImport } from './routes/(app)/insecticides/$insecticideId'
import { Route as appDocumentsCreateRouteImport } from './routes/(app)/documents/create'
import { Route as appDocumentsDocumentIdRouteImport } from './routes/(app)/documents/$documentId'
import { Route as appDocumentCategoriesCreateRouteImport } from './routes/(app)/document-categories/create'
import { Route as appDocumentCategoriesCategoryIdRouteImport } from './routes/(app)/document-categories/$categoryId'
import { Route as appCategoriesCreateRouteImport } from './routes/(app)/categories/create'
import { Route as appCategoriesCategoryIdRouteImport } from './routes/(app)/categories/$categoryId'
import { Route as appSprayScheduleSprayScheduleIdEditRouteImport } from './routes/(app)/spray-schedule/$sprayScheduleId_.edit'
import { Route as appNoticesNoticeIdEditRouteImport } from './routes/(app)/notices/$noticeId_.edit'
import { Route as appMeetingsMeetingIdEditRouteImport } from './routes/(app)/meetings/$meetingId_.edit'
import { Route as appJobPostingsPostingIdEditRouteImport } from './routes/(app)/job-postings/$postingId_.edit'
import { Route as appInsecticidesInsecticideIdEditRouteImport } from './routes/(app)/insecticides/$insecticideId_.edit'
import { Route as appDocumentsDocumentIdEditRouteImport } from './routes/(app)/documents/$documentId_.edit'
import { Route as appDocumentCategoriesCategoryIdEditRouteImport } from './routes/(app)/document-categories/$categoryId_.edit'
import { Route as appCategoriesCategoryIdEditRouteImport } from './routes/(app)/categories/$categoryId_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSprayScheduleRouteRoute = appSprayScheduleRouteRouteImport.update({
  id: '/spray-schedule',
  path: '/spray-schedule',
  getParentRoute: () => appRouteRoute,
} as any)
const appPublicRequestsRouteRoute = appPublicRequestsRouteRouteImport.update({
  id: '/public-requests',
  path: '/public-requests',
  getParentRoute: () => appRouteRoute,
} as any)
const appNoticesRouteRoute = appNoticesRouteRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => appRouteRoute,
} as any)
const appMeetingsRouteRoute = appMeetingsRouteRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => appRouteRoute,
} as any)
const appJobPostingsRouteRoute = appJobPostingsRouteRouteImport.update({
  id: '/job-postings',
  path: '/job-postings',
  getParentRoute: () => appRouteRoute,
} as any)
const appInsecticidesRouteRoute = appInsecticidesRouteRouteImport.update({
  id: '/insecticides',
  path: '/insecticides',
  getParentRoute: () => appRouteRoute,
} as any)
const appDocumentsRouteRoute = appDocumentsRouteRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => appRouteRoute,
} as any)
const appDocumentCategoriesRouteRoute =
  appDocumentCategoriesRouteRouteImport.update({
    id: '/document-categories',
    path: '/document-categories',
    getParentRoute: () => appRouteRoute,
  } as any)
const appCategoriesRouteRoute = appCategoriesRouteRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => appRouteRoute,
} as any)
const appWeeklyActivityIndexRoute = appWeeklyActivityIndexRouteImport.update({
  id: '/weekly-activity/',
  path: '/weekly-activity/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSprayScheduleIndexRoute = appSprayScheduleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appSprayScheduleRouteRoute,
} as any)
const appPublicRequestsIndexRoute = appPublicRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appPublicRequestsRouteRoute,
} as any)
const appNoticesIndexRoute = appNoticesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appMeetingsIndexRoute = appMeetingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appMeetingsRouteRoute,
} as any)
const appJobPostingsIndexRoute = appJobPostingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appJobPostingsRouteRoute,
} as any)
const appInsecticidesIndexRoute = appInsecticidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appInsecticidesRouteRoute,
} as any)
const appDocumentsIndexRoute = appDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDocumentsRouteRoute,
} as any)
const appDocumentCategoriesIndexRoute =
  appDocumentCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appDocumentCategoriesRouteRoute,
  } as any)
const appCategoriesIndexRoute = appCategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appCategoriesRouteRoute,
} as any)
const appSprayScheduleCreateRoute = appSprayScheduleCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appSprayScheduleRouteRoute,
} as any)
const appSprayScheduleSprayScheduleIdRoute =
  appSprayScheduleSprayScheduleIdRouteImport.update({
    id: '/$sprayScheduleId',
    path: '/$sprayScheduleId',
    getParentRoute: () => appSprayScheduleRouteRoute,
  } as any)
const appPublicRequestsRequestIdRoute =
  appPublicRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => appPublicRequestsRouteRoute,
  } as any)
const appNoticesCreateRoute = appNoticesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appNoticesNoticeIdRoute = appNoticesNoticeIdRouteImport.update({
  id: '/$noticeId',
  path: '/$noticeId',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appMeetingsCreateRoute = appMeetingsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appMeetingsRouteRoute,
} as any)
const appMeetingsMeetingIdRoute = appMeetingsMeetingIdRouteImport.update({
  id: '/$meetingId',
  path: '/$meetingId',
  getParentRoute: () => appMeetingsRouteRoute,
} as any)
const appJobPostingsCreateRoute = appJobPostingsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appJobPostingsRouteRoute,
} as any)
const appJobPostingsPostingIdRoute = appJobPostingsPostingIdRouteImport.update({
  id: '/$postingId',
  path: '/$postingId',
  getParentRoute: () => appJobPostingsRouteRoute,
} as any)
const appInsecticidesCreateRoute = appInsecticidesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appInsecticidesRouteRoute,
} as any)
const appInsecticidesInsecticideIdRoute =
  appInsecticidesInsecticideIdRouteImport.update({
    id: '/$insecticideId',
    path: '/$insecticideId',
    getParentRoute: () => appInsecticidesRouteRoute,
  } as any)
const appDocumentsCreateRoute = appDocumentsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appDocumentsRouteRoute,
} as any)
const appDocumentsDocumentIdRoute = appDocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => appDocumentsRouteRoute,
} as any)
const appDocumentCategoriesCreateRoute =
  appDocumentCategoriesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => appDocumentCategoriesRouteRoute,
  } as any)
const appDocumentCategoriesCategoryIdRoute =
  appDocumentCategoriesCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => appDocumentCategoriesRouteRoute,
  } as any)
const appCategoriesCreateRoute = appCategoriesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appCategoriesRouteRoute,
} as any)
const appCategoriesCategoryIdRoute = appCategoriesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => appCategoriesRouteRoute,
} as any)
const appSprayScheduleSprayScheduleIdEditRoute =
  appSprayScheduleSprayScheduleIdEditRouteImport.update({
    id: '/$sprayScheduleId_/edit',
    path: '/$sprayScheduleId/edit',
    getParentRoute: () => appSprayScheduleRouteRoute,
  } as any)
const appNoticesNoticeIdEditRoute = appNoticesNoticeIdEditRouteImport.update({
  id: '/$noticeId_/edit',
  path: '/$noticeId/edit',
  getParentRoute: () => appNoticesRouteRoute,
} as any)
const appMeetingsMeetingIdEditRoute =
  appMeetingsMeetingIdEditRouteImport.update({
    id: '/$meetingId_/edit',
    path: '/$meetingId/edit',
    getParentRoute: () => appMeetingsRouteRoute,
  } as any)
const appJobPostingsPostingIdEditRoute =
  appJobPostingsPostingIdEditRouteImport.update({
    id: '/$postingId_/edit',
    path: '/$postingId/edit',
    getParentRoute: () => appJobPostingsRouteRoute,
  } as any)
const appInsecticidesInsecticideIdEditRoute =
  appInsecticidesInsecticideIdEditRouteImport.update({
    id: '/$insecticideId_/edit',
    path: '/$insecticideId/edit',
    getParentRoute: () => appInsecticidesRouteRoute,
  } as any)
const appDocumentsDocumentIdEditRoute =
  appDocumentsDocumentIdEditRouteImport.update({
    id: '/$documentId_/edit',
    path: '/$documentId/edit',
    getParentRoute: () => appDocumentsRouteRoute,
  } as any)
const appDocumentCategoriesCategoryIdEditRoute =
  appDocumentCategoriesCategoryIdEditRouteImport.update({
    id: '/$categoryId_/edit',
    path: '/$categoryId/edit',
    getParentRoute: () => appDocumentCategoriesRouteRoute,
  } as any)
const appCategoriesCategoryIdEditRoute =
  appCategoriesCategoryIdEditRouteImport.update({
    id: '/$categoryId_/edit',
    path: '/$categoryId/edit',
    getParentRoute: () => appCategoriesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/categories': typeof appCategoriesRouteRouteWithChildren
  '/document-categories': typeof appDocumentCategoriesRouteRouteWithChildren
  '/documents': typeof appDocumentsRouteRouteWithChildren
  '/insecticides': typeof appInsecticidesRouteRouteWithChildren
  '/job-postings': typeof appJobPostingsRouteRouteWithChildren
  '/meetings': typeof appMeetingsRouteRouteWithChildren
  '/notices': typeof appNoticesRouteRouteWithChildren
  '/public-requests': typeof appPublicRequestsRouteRouteWithChildren
  '/spray-schedule': typeof appSprayScheduleRouteRouteWithChildren
  '/': typeof appIndexRoute
  '/categories/$categoryId': typeof appCategoriesCategoryIdRoute
  '/categories/create': typeof appCategoriesCreateRoute
  '/document-categories/$categoryId': typeof appDocumentCategoriesCategoryIdRoute
  '/document-categories/create': typeof appDocumentCategoriesCreateRoute
  '/documents/$documentId': typeof appDocumentsDocumentIdRoute
  '/documents/create': typeof appDocumentsCreateRoute
  '/insecticides/$insecticideId': typeof appInsecticidesInsecticideIdRoute
  '/insecticides/create': typeof appInsecticidesCreateRoute
  '/job-postings/$postingId': typeof appJobPostingsPostingIdRoute
  '/job-postings/create': typeof appJobPostingsCreateRoute
  '/meetings/$meetingId': typeof appMeetingsMeetingIdRoute
  '/meetings/create': typeof appMeetingsCreateRoute
  '/notices/$noticeId': typeof appNoticesNoticeIdRoute
  '/notices/create': typeof appNoticesCreateRoute
  '/public-requests/$requestId': typeof appPublicRequestsRequestIdRoute
  '/spray-schedule/$sprayScheduleId': typeof appSprayScheduleSprayScheduleIdRoute
  '/spray-schedule/create': typeof appSprayScheduleCreateRoute
  '/categories/': typeof appCategoriesIndexRoute
  '/document-categories/': typeof appDocumentCategoriesIndexRoute
  '/documents/': typeof appDocumentsIndexRoute
  '/insecticides/': typeof appInsecticidesIndexRoute
  '/job-postings/': typeof appJobPostingsIndexRoute
  '/meetings/': typeof appMeetingsIndexRoute
  '/notices/': typeof appNoticesIndexRoute
  '/public-requests/': typeof appPublicRequestsIndexRoute
  '/spray-schedule/': typeof appSprayScheduleIndexRoute
  '/weekly-activity/': typeof appWeeklyActivityIndexRoute
  '/categories/$categoryId/edit': typeof appCategoriesCategoryIdEditRoute
  '/document-categories/$categoryId/edit': typeof appDocumentCategoriesCategoryIdEditRoute
  '/documents/$documentId/edit': typeof appDocumentsDocumentIdEditRoute
  '/insecticides/$insecticideId/edit': typeof appInsecticidesInsecticideIdEditRoute
  '/job-postings/$postingId/edit': typeof appJobPostingsPostingIdEditRoute
  '/meetings/$meetingId/edit': typeof appMeetingsMeetingIdEditRoute
  '/notices/$noticeId/edit': typeof appNoticesNoticeIdEditRoute
  '/spray-schedule/$sprayScheduleId/edit': typeof appSprayScheduleSprayScheduleIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof appIndexRoute
  '/categories/$categoryId': typeof appCategoriesCategoryIdRoute
  '/categories/create': typeof appCategoriesCreateRoute
  '/document-categories/$categoryId': typeof appDocumentCategoriesCategoryIdRoute
  '/document-categories/create': typeof appDocumentCategoriesCreateRoute
  '/documents/$documentId': typeof appDocumentsDocumentIdRoute
  '/documents/create': typeof appDocumentsCreateRoute
  '/insecticides/$insecticideId': typeof appInsecticidesInsecticideIdRoute
  '/insecticides/create': typeof appInsecticidesCreateRoute
  '/job-postings/$postingId': typeof appJobPostingsPostingIdRoute
  '/job-postings/create': typeof appJobPostingsCreateRoute
  '/meetings/$meetingId': typeof appMeetingsMeetingIdRoute
  '/meetings/create': typeof appMeetingsCreateRoute
  '/notices/$noticeId': typeof appNoticesNoticeIdRoute
  '/notices/create': typeof appNoticesCreateRoute
  '/public-requests/$requestId': typeof appPublicRequestsRequestIdRoute
  '/spray-schedule/$sprayScheduleId': typeof appSprayScheduleSprayScheduleIdRoute
  '/spray-schedule/create': typeof appSprayScheduleCreateRoute
  '/categories': typeof appCategoriesIndexRoute
  '/document-categories': typeof appDocumentCategoriesIndexRoute
  '/documents': typeof appDocumentsIndexRoute
  '/insecticides': typeof appInsecticidesIndexRoute
  '/job-postings': typeof appJobPostingsIndexRoute
  '/meetings': typeof appMeetingsIndexRoute
  '/notices': typeof appNoticesIndexRoute
  '/public-requests': typeof appPublicRequestsIndexRoute
  '/spray-schedule': typeof appSprayScheduleIndexRoute
  '/weekly-activity': typeof appWeeklyActivityIndexRoute
  '/categories/$categoryId/edit': typeof appCategoriesCategoryIdEditRoute
  '/document-categories/$categoryId/edit': typeof appDocumentCategoriesCategoryIdEditRoute
  '/documents/$documentId/edit': typeof appDocumentsDocumentIdEditRoute
  '/insecticides/$insecticideId/edit': typeof appInsecticidesInsecticideIdEditRoute
  '/job-postings/$postingId/edit': typeof appJobPostingsPostingIdEditRoute
  '/meetings/$meetingId/edit': typeof appMeetingsMeetingIdEditRoute
  '/notices/$noticeId/edit': typeof appNoticesNoticeIdEditRoute
  '/spray-schedule/$sprayScheduleId/edit': typeof appSprayScheduleSprayScheduleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(app)/categories': typeof appCategoriesRouteRouteWithChildren
  '/(app)/document-categories': typeof appDocumentCategoriesRouteRouteWithChildren
  '/(app)/documents': typeof appDocumentsRouteRouteWithChildren
  '/(app)/insecticides': typeof appInsecticidesRouteRouteWithChildren
  '/(app)/job-postings': typeof appJobPostingsRouteRouteWithChildren
  '/(app)/meetings': typeof appMeetingsRouteRouteWithChildren
  '/(app)/notices': typeof appNoticesRouteRouteWithChildren
  '/(app)/public-requests': typeof appPublicRequestsRouteRouteWithChildren
  '/(app)/spray-schedule': typeof appSprayScheduleRouteRouteWithChildren
  '/(app)/': typeof appIndexRoute
  '/(app)/categories/$categoryId': typeof appCategoriesCategoryIdRoute
  '/(app)/categories/create': typeof appCategoriesCreateRoute
  '/(app)/document-categories/$categoryId': typeof appDocumentCategoriesCategoryIdRoute
  '/(app)/document-categories/create': typeof appDocumentCategoriesCreateRoute
  '/(app)/documents/$documentId': typeof appDocumentsDocumentIdRoute
  '/(app)/documents/create': typeof appDocumentsCreateRoute
  '/(app)/insecticides/$insecticideId': typeof appInsecticidesInsecticideIdRoute
  '/(app)/insecticides/create': typeof appInsecticidesCreateRoute
  '/(app)/job-postings/$postingId': typeof appJobPostingsPostingIdRoute
  '/(app)/job-postings/create': typeof appJobPostingsCreateRoute
  '/(app)/meetings/$meetingId': typeof appMeetingsMeetingIdRoute
  '/(app)/meetings/create': typeof appMeetingsCreateRoute
  '/(app)/notices/$noticeId': typeof appNoticesNoticeIdRoute
  '/(app)/notices/create': typeof appNoticesCreateRoute
  '/(app)/public-requests/$requestId': typeof appPublicRequestsRequestIdRoute
  '/(app)/spray-schedule/$sprayScheduleId': typeof appSprayScheduleSprayScheduleIdRoute
  '/(app)/spray-schedule/create': typeof appSprayScheduleCreateRoute
  '/(app)/categories/': typeof appCategoriesIndexRoute
  '/(app)/document-categories/': typeof appDocumentCategoriesIndexRoute
  '/(app)/documents/': typeof appDocumentsIndexRoute
  '/(app)/insecticides/': typeof appInsecticidesIndexRoute
  '/(app)/job-postings/': typeof appJobPostingsIndexRoute
  '/(app)/meetings/': typeof appMeetingsIndexRoute
  '/(app)/notices/': typeof appNoticesIndexRoute
  '/(app)/public-requests/': typeof appPublicRequestsIndexRoute
  '/(app)/spray-schedule/': typeof appSprayScheduleIndexRoute
  '/(app)/weekly-activity/': typeof appWeeklyActivityIndexRoute
  '/(app)/categories/$categoryId_/edit': typeof appCategoriesCategoryIdEditRoute
  '/(app)/document-categories/$categoryId_/edit': typeof appDocumentCategoriesCategoryIdEditRoute
  '/(app)/documents/$documentId_/edit': typeof appDocumentsDocumentIdEditRoute
  '/(app)/insecticides/$insecticideId_/edit': typeof appInsecticidesInsecticideIdEditRoute
  '/(app)/job-postings/$postingId_/edit': typeof appJobPostingsPostingIdEditRoute
  '/(app)/meetings/$meetingId_/edit': typeof appMeetingsMeetingIdEditRoute
  '/(app)/notices/$noticeId_/edit': typeof appNoticesNoticeIdEditRoute
  '/(app)/spray-schedule/$sprayScheduleId_/edit': typeof appSprayScheduleSprayScheduleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/categories'
    | '/document-categories'
    | '/documents'
    | '/insecticides'
    | '/job-postings'
    | '/meetings'
    | '/notices'
    | '/public-requests'
    | '/spray-schedule'
    | '/'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/document-categories/$categoryId'
    | '/document-categories/create'
    | '/documents/$documentId'
    | '/documents/create'
    | '/insecticides/$insecticideId'
    | '/insecticides/create'
    | '/job-postings/$postingId'
    | '/job-postings/create'
    | '/meetings/$meetingId'
    | '/meetings/create'
    | '/notices/$noticeId'
    | '/notices/create'
    | '/public-requests/$requestId'
    | '/spray-schedule/$sprayScheduleId'
    | '/spray-schedule/create'
    | '/categories/'
    | '/document-categories/'
    | '/documents/'
    | '/insecticides/'
    | '/job-postings/'
    | '/meetings/'
    | '/notices/'
    | '/public-requests/'
    | '/spray-schedule/'
    | '/weekly-activity/'
    | '/categories/$categoryId/edit'
    | '/document-categories/$categoryId/edit'
    | '/documents/$documentId/edit'
    | '/insecticides/$insecticideId/edit'
    | '/job-postings/$postingId/edit'
    | '/meetings/$meetingId/edit'
    | '/notices/$noticeId/edit'
    | '/spray-schedule/$sprayScheduleId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/document-categories/$categoryId'
    | '/document-categories/create'
    | '/documents/$documentId'
    | '/documents/create'
    | '/insecticides/$insecticideId'
    | '/insecticides/create'
    | '/job-postings/$postingId'
    | '/job-postings/create'
    | '/meetings/$meetingId'
    | '/meetings/create'
    | '/notices/$noticeId'
    | '/notices/create'
    | '/public-requests/$requestId'
    | '/spray-schedule/$sprayScheduleId'
    | '/spray-schedule/create'
    | '/categories'
    | '/document-categories'
    | '/documents'
    | '/insecticides'
    | '/job-postings'
    | '/meetings'
    | '/notices'
    | '/public-requests'
    | '/spray-schedule'
    | '/weekly-activity'
    | '/categories/$categoryId/edit'
    | '/document-categories/$categoryId/edit'
    | '/documents/$documentId/edit'
    | '/insecticides/$insecticideId/edit'
    | '/job-postings/$postingId/edit'
    | '/meetings/$meetingId/edit'
    | '/notices/$noticeId/edit'
    | '/spray-schedule/$sprayScheduleId/edit'
  id:
    | '__root__'
    | '/(app)'
    | '/login'
    | '/(app)/categories'
    | '/(app)/document-categories'
    | '/(app)/documents'
    | '/(app)/insecticides'
    | '/(app)/job-postings'
    | '/(app)/meetings'
    | '/(app)/notices'
    | '/(app)/public-requests'
    | '/(app)/spray-schedule'
    | '/(app)/'
    | '/(app)/categories/$categoryId'
    | '/(app)/categories/create'
    | '/(app)/document-categories/$categoryId'
    | '/(app)/document-categories/create'
    | '/(app)/documents/$documentId'
    | '/(app)/documents/create'
    | '/(app)/insecticides/$insecticideId'
    | '/(app)/insecticides/create'
    | '/(app)/job-postings/$postingId'
    | '/(app)/job-postings/create'
    | '/(app)/meetings/$meetingId'
    | '/(app)/meetings/create'
    | '/(app)/notices/$noticeId'
    | '/(app)/notices/create'
    | '/(app)/public-requests/$requestId'
    | '/(app)/spray-schedule/$sprayScheduleId'
    | '/(app)/spray-schedule/create'
    | '/(app)/categories/'
    | '/(app)/document-categories/'
    | '/(app)/documents/'
    | '/(app)/insecticides/'
    | '/(app)/job-postings/'
    | '/(app)/meetings/'
    | '/(app)/notices/'
    | '/(app)/public-requests/'
    | '/(app)/spray-schedule/'
    | '/(app)/weekly-activity/'
    | '/(app)/categories/$categoryId_/edit'
    | '/(app)/document-categories/$categoryId_/edit'
    | '/(app)/documents/$documentId_/edit'
    | '/(app)/insecticides/$insecticideId_/edit'
    | '/(app)/job-postings/$postingId_/edit'
    | '/(app)/meetings/$meetingId_/edit'
    | '/(app)/notices/$noticeId_/edit'
    | '/(app)/spray-schedule/$sprayScheduleId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/spray-schedule': {
      id: '/(app)/spray-schedule'
      path: '/spray-schedule'
      fullPath: '/spray-schedule'
      preLoaderRoute: typeof appSprayScheduleRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/public-requests': {
      id: '/(app)/public-requests'
      path: '/public-requests'
      fullPath: '/public-requests'
      preLoaderRoute: typeof appPublicRequestsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/notices': {
      id: '/(app)/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof appNoticesRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/meetings': {
      id: '/(app)/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof appMeetingsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/job-postings': {
      id: '/(app)/job-postings'
      path: '/job-postings'
      fullPath: '/job-postings'
      preLoaderRoute: typeof appJobPostingsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/insecticides': {
      id: '/(app)/insecticides'
      path: '/insecticides'
      fullPath: '/insecticides'
      preLoaderRoute: typeof appInsecticidesRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/documents': {
      id: '/(app)/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof appDocumentsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/document-categories': {
      id: '/(app)/document-categories'
      path: '/document-categories'
      fullPath: '/document-categories'
      preLoaderRoute: typeof appDocumentCategoriesRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/categories': {
      id: '/(app)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof appCategoriesRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/weekly-activity/': {
      id: '/(app)/weekly-activity/'
      path: '/weekly-activity'
      fullPath: '/weekly-activity/'
      preLoaderRoute: typeof appWeeklyActivityIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/spray-schedule/': {
      id: '/(app)/spray-schedule/'
      path: '/'
      fullPath: '/spray-schedule/'
      preLoaderRoute: typeof appSprayScheduleIndexRouteImport
      parentRoute: typeof appSprayScheduleRouteRoute
    }
    '/(app)/public-requests/': {
      id: '/(app)/public-requests/'
      path: '/'
      fullPath: '/public-requests/'
      preLoaderRoute: typeof appPublicRequestsIndexRouteImport
      parentRoute: typeof appPublicRequestsRouteRoute
    }
    '/(app)/notices/': {
      id: '/(app)/notices/'
      path: '/'
      fullPath: '/notices/'
      preLoaderRoute: typeof appNoticesIndexRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/meetings/': {
      id: '/(app)/meetings/'
      path: '/'
      fullPath: '/meetings/'
      preLoaderRoute: typeof appMeetingsIndexRouteImport
      parentRoute: typeof appMeetingsRouteRoute
    }
    '/(app)/job-postings/': {
      id: '/(app)/job-postings/'
      path: '/'
      fullPath: '/job-postings/'
      preLoaderRoute: typeof appJobPostingsIndexRouteImport
      parentRoute: typeof appJobPostingsRouteRoute
    }
    '/(app)/insecticides/': {
      id: '/(app)/insecticides/'
      path: '/'
      fullPath: '/insecticides/'
      preLoaderRoute: typeof appInsecticidesIndexRouteImport
      parentRoute: typeof appInsecticidesRouteRoute
    }
    '/(app)/documents/': {
      id: '/(app)/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof appDocumentsIndexRouteImport
      parentRoute: typeof appDocumentsRouteRoute
    }
    '/(app)/document-categories/': {
      id: '/(app)/document-categories/'
      path: '/'
      fullPath: '/document-categories/'
      preLoaderRoute: typeof appDocumentCategoriesIndexRouteImport
      parentRoute: typeof appDocumentCategoriesRouteRoute
    }
    '/(app)/categories/': {
      id: '/(app)/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof appCategoriesIndexRouteImport
      parentRoute: typeof appCategoriesRouteRoute
    }
    '/(app)/spray-schedule/create': {
      id: '/(app)/spray-schedule/create'
      path: '/create'
      fullPath: '/spray-schedule/create'
      preLoaderRoute: typeof appSprayScheduleCreateRouteImport
      parentRoute: typeof appSprayScheduleRouteRoute
    }
    '/(app)/spray-schedule/$sprayScheduleId': {
      id: '/(app)/spray-schedule/$sprayScheduleId'
      path: '/$sprayScheduleId'
      fullPath: '/spray-schedule/$sprayScheduleId'
      preLoaderRoute: typeof appSprayScheduleSprayScheduleIdRouteImport
      parentRoute: typeof appSprayScheduleRouteRoute
    }
    '/(app)/public-requests/$requestId': {
      id: '/(app)/public-requests/$requestId'
      path: '/$requestId'
      fullPath: '/public-requests/$requestId'
      preLoaderRoute: typeof appPublicRequestsRequestIdRouteImport
      parentRoute: typeof appPublicRequestsRouteRoute
    }
    '/(app)/notices/create': {
      id: '/(app)/notices/create'
      path: '/create'
      fullPath: '/notices/create'
      preLoaderRoute: typeof appNoticesCreateRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/notices/$noticeId': {
      id: '/(app)/notices/$noticeId'
      path: '/$noticeId'
      fullPath: '/notices/$noticeId'
      preLoaderRoute: typeof appNoticesNoticeIdRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/meetings/create': {
      id: '/(app)/meetings/create'
      path: '/create'
      fullPath: '/meetings/create'
      preLoaderRoute: typeof appMeetingsCreateRouteImport
      parentRoute: typeof appMeetingsRouteRoute
    }
    '/(app)/meetings/$meetingId': {
      id: '/(app)/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof appMeetingsMeetingIdRouteImport
      parentRoute: typeof appMeetingsRouteRoute
    }
    '/(app)/job-postings/create': {
      id: '/(app)/job-postings/create'
      path: '/create'
      fullPath: '/job-postings/create'
      preLoaderRoute: typeof appJobPostingsCreateRouteImport
      parentRoute: typeof appJobPostingsRouteRoute
    }
    '/(app)/job-postings/$postingId': {
      id: '/(app)/job-postings/$postingId'
      path: '/$postingId'
      fullPath: '/job-postings/$postingId'
      preLoaderRoute: typeof appJobPostingsPostingIdRouteImport
      parentRoute: typeof appJobPostingsRouteRoute
    }
    '/(app)/insecticides/create': {
      id: '/(app)/insecticides/create'
      path: '/create'
      fullPath: '/insecticides/create'
      preLoaderRoute: typeof appInsecticidesCreateRouteImport
      parentRoute: typeof appInsecticidesRouteRoute
    }
    '/(app)/insecticides/$insecticideId': {
      id: '/(app)/insecticides/$insecticideId'
      path: '/$insecticideId'
      fullPath: '/insecticides/$insecticideId'
      preLoaderRoute: typeof appInsecticidesInsecticideIdRouteImport
      parentRoute: typeof appInsecticidesRouteRoute
    }
    '/(app)/documents/create': {
      id: '/(app)/documents/create'
      path: '/create'
      fullPath: '/documents/create'
      preLoaderRoute: typeof appDocumentsCreateRouteImport
      parentRoute: typeof appDocumentsRouteRoute
    }
    '/(app)/documents/$documentId': {
      id: '/(app)/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof appDocumentsDocumentIdRouteImport
      parentRoute: typeof appDocumentsRouteRoute
    }
    '/(app)/document-categories/create': {
      id: '/(app)/document-categories/create'
      path: '/create'
      fullPath: '/document-categories/create'
      preLoaderRoute: typeof appDocumentCategoriesCreateRouteImport
      parentRoute: typeof appDocumentCategoriesRouteRoute
    }
    '/(app)/document-categories/$categoryId': {
      id: '/(app)/document-categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/document-categories/$categoryId'
      preLoaderRoute: typeof appDocumentCategoriesCategoryIdRouteImport
      parentRoute: typeof appDocumentCategoriesRouteRoute
    }
    '/(app)/categories/create': {
      id: '/(app)/categories/create'
      path: '/create'
      fullPath: '/categories/create'
      preLoaderRoute: typeof appCategoriesCreateRouteImport
      parentRoute: typeof appCategoriesRouteRoute
    }
    '/(app)/categories/$categoryId': {
      id: '/(app)/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof appCategoriesCategoryIdRouteImport
      parentRoute: typeof appCategoriesRouteRoute
    }
    '/(app)/spray-schedule/$sprayScheduleId_/edit': {
      id: '/(app)/spray-schedule/$sprayScheduleId_/edit'
      path: '/$sprayScheduleId/edit'
      fullPath: '/spray-schedule/$sprayScheduleId/edit'
      preLoaderRoute: typeof appSprayScheduleSprayScheduleIdEditRouteImport
      parentRoute: typeof appSprayScheduleRouteRoute
    }
    '/(app)/notices/$noticeId_/edit': {
      id: '/(app)/notices/$noticeId_/edit'
      path: '/$noticeId/edit'
      fullPath: '/notices/$noticeId/edit'
      preLoaderRoute: typeof appNoticesNoticeIdEditRouteImport
      parentRoute: typeof appNoticesRouteRoute
    }
    '/(app)/meetings/$meetingId_/edit': {
      id: '/(app)/meetings/$meetingId_/edit'
      path: '/$meetingId/edit'
      fullPath: '/meetings/$meetingId/edit'
      preLoaderRoute: typeof appMeetingsMeetingIdEditRouteImport
      parentRoute: typeof appMeetingsRouteRoute
    }
    '/(app)/job-postings/$postingId_/edit': {
      id: '/(app)/job-postings/$postingId_/edit'
      path: '/$postingId/edit'
      fullPath: '/job-postings/$postingId/edit'
      preLoaderRoute: typeof appJobPostingsPostingIdEditRouteImport
      parentRoute: typeof appJobPostingsRouteRoute
    }
    '/(app)/insecticides/$insecticideId_/edit': {
      id: '/(app)/insecticides/$insecticideId_/edit'
      path: '/$insecticideId/edit'
      fullPath: '/insecticides/$insecticideId/edit'
      preLoaderRoute: typeof appInsecticidesInsecticideIdEditRouteImport
      parentRoute: typeof appInsecticidesRouteRoute
    }
    '/(app)/documents/$documentId_/edit': {
      id: '/(app)/documents/$documentId_/edit'
      path: '/$documentId/edit'
      fullPath: '/documents/$documentId/edit'
      preLoaderRoute: typeof appDocumentsDocumentIdEditRouteImport
      parentRoute: typeof appDocumentsRouteRoute
    }
    '/(app)/document-categories/$categoryId_/edit': {
      id: '/(app)/document-categories/$categoryId_/edit'
      path: '/$categoryId/edit'
      fullPath: '/document-categories/$categoryId/edit'
      preLoaderRoute: typeof appDocumentCategoriesCategoryIdEditRouteImport
      parentRoute: typeof appDocumentCategoriesRouteRoute
    }
    '/(app)/categories/$categoryId_/edit': {
      id: '/(app)/categories/$categoryId_/edit'
      path: '/$categoryId/edit'
      fullPath: '/categories/$categoryId/edit'
      preLoaderRoute: typeof appCategoriesCategoryIdEditRouteImport
      parentRoute: typeof appCategoriesRouteRoute
    }
  }
}

interface appCategoriesRouteRouteChildren {
  appCategoriesCategoryIdRoute: typeof appCategoriesCategoryIdRoute
  appCategoriesCreateRoute: typeof appCategoriesCreateRoute
  appCategoriesIndexRoute: typeof appCategoriesIndexRoute
  appCategoriesCategoryIdEditRoute: typeof appCategoriesCategoryIdEditRoute
}

const appCategoriesRouteRouteChildren: appCategoriesRouteRouteChildren = {
  appCategoriesCategoryIdRoute: appCategoriesCategoryIdRoute,
  appCategoriesCreateRoute: appCategoriesCreateRoute,
  appCategoriesIndexRoute: appCategoriesIndexRoute,
  appCategoriesCategoryIdEditRoute: appCategoriesCategoryIdEditRoute,
}

const appCategoriesRouteRouteWithChildren =
  appCategoriesRouteRoute._addFileChildren(appCategoriesRouteRouteChildren)

interface appDocumentCategoriesRouteRouteChildren {
  appDocumentCategoriesCategoryIdRoute: typeof appDocumentCategoriesCategoryIdRoute
  appDocumentCategoriesCreateRoute: typeof appDocumentCategoriesCreateRoute
  appDocumentCategoriesIndexRoute: typeof appDocumentCategoriesIndexRoute
  appDocumentCategoriesCategoryIdEditRoute: typeof appDocumentCategoriesCategoryIdEditRoute
}

const appDocumentCategoriesRouteRouteChildren: appDocumentCategoriesRouteRouteChildren =
  {
    appDocumentCategoriesCategoryIdRoute: appDocumentCategoriesCategoryIdRoute,
    appDocumentCategoriesCreateRoute: appDocumentCategoriesCreateRoute,
    appDocumentCategoriesIndexRoute: appDocumentCategoriesIndexRoute,
    appDocumentCategoriesCategoryIdEditRoute:
      appDocumentCategoriesCategoryIdEditRoute,
  }

const appDocumentCategoriesRouteRouteWithChildren =
  appDocumentCategoriesRouteRoute._addFileChildren(
    appDocumentCategoriesRouteRouteChildren,
  )

interface appDocumentsRouteRouteChildren {
  appDocumentsDocumentIdRoute: typeof appDocumentsDocumentIdRoute
  appDocumentsCreateRoute: typeof appDocumentsCreateRoute
  appDocumentsIndexRoute: typeof appDocumentsIndexRoute
  appDocumentsDocumentIdEditRoute: typeof appDocumentsDocumentIdEditRoute
}

const appDocumentsRouteRouteChildren: appDocumentsRouteRouteChildren = {
  appDocumentsDocumentIdRoute: appDocumentsDocumentIdRoute,
  appDocumentsCreateRoute: appDocumentsCreateRoute,
  appDocumentsIndexRoute: appDocumentsIndexRoute,
  appDocumentsDocumentIdEditRoute: appDocumentsDocumentIdEditRoute,
}

const appDocumentsRouteRouteWithChildren =
  appDocumentsRouteRoute._addFileChildren(appDocumentsRouteRouteChildren)

interface appInsecticidesRouteRouteChildren {
  appInsecticidesInsecticideIdRoute: typeof appInsecticidesInsecticideIdRoute
  appInsecticidesCreateRoute: typeof appInsecticidesCreateRoute
  appInsecticidesIndexRoute: typeof appInsecticidesIndexRoute
  appInsecticidesInsecticideIdEditRoute: typeof appInsecticidesInsecticideIdEditRoute
}

const appInsecticidesRouteRouteChildren: appInsecticidesRouteRouteChildren = {
  appInsecticidesInsecticideIdRoute: appInsecticidesInsecticideIdRoute,
  appInsecticidesCreateRoute: appInsecticidesCreateRoute,
  appInsecticidesIndexRoute: appInsecticidesIndexRoute,
  appInsecticidesInsecticideIdEditRoute: appInsecticidesInsecticideIdEditRoute,
}

const appInsecticidesRouteRouteWithChildren =
  appInsecticidesRouteRoute._addFileChildren(appInsecticidesRouteRouteChildren)

interface appJobPostingsRouteRouteChildren {
  appJobPostingsPostingIdRoute: typeof appJobPostingsPostingIdRoute
  appJobPostingsCreateRoute: typeof appJobPostingsCreateRoute
  appJobPostingsIndexRoute: typeof appJobPostingsIndexRoute
  appJobPostingsPostingIdEditRoute: typeof appJobPostingsPostingIdEditRoute
}

const appJobPostingsRouteRouteChildren: appJobPostingsRouteRouteChildren = {
  appJobPostingsPostingIdRoute: appJobPostingsPostingIdRoute,
  appJobPostingsCreateRoute: appJobPostingsCreateRoute,
  appJobPostingsIndexRoute: appJobPostingsIndexRoute,
  appJobPostingsPostingIdEditRoute: appJobPostingsPostingIdEditRoute,
}

const appJobPostingsRouteRouteWithChildren =
  appJobPostingsRouteRoute._addFileChildren(appJobPostingsRouteRouteChildren)

interface appMeetingsRouteRouteChildren {
  appMeetingsMeetingIdRoute: typeof appMeetingsMeetingIdRoute
  appMeetingsCreateRoute: typeof appMeetingsCreateRoute
  appMeetingsIndexRoute: typeof appMeetingsIndexRoute
  appMeetingsMeetingIdEditRoute: typeof appMeetingsMeetingIdEditRoute
}

const appMeetingsRouteRouteChildren: appMeetingsRouteRouteChildren = {
  appMeetingsMeetingIdRoute: appMeetingsMeetingIdRoute,
  appMeetingsCreateRoute: appMeetingsCreateRoute,
  appMeetingsIndexRoute: appMeetingsIndexRoute,
  appMeetingsMeetingIdEditRoute: appMeetingsMeetingIdEditRoute,
}

const appMeetingsRouteRouteWithChildren =
  appMeetingsRouteRoute._addFileChildren(appMeetingsRouteRouteChildren)

interface appNoticesRouteRouteChildren {
  appNoticesNoticeIdRoute: typeof appNoticesNoticeIdRoute
  appNoticesCreateRoute: typeof appNoticesCreateRoute
  appNoticesIndexRoute: typeof appNoticesIndexRoute
  appNoticesNoticeIdEditRoute: typeof appNoticesNoticeIdEditRoute
}

const appNoticesRouteRouteChildren: appNoticesRouteRouteChildren = {
  appNoticesNoticeIdRoute: appNoticesNoticeIdRoute,
  appNoticesCreateRoute: appNoticesCreateRoute,
  appNoticesIndexRoute: appNoticesIndexRoute,
  appNoticesNoticeIdEditRoute: appNoticesNoticeIdEditRoute,
}

const appNoticesRouteRouteWithChildren = appNoticesRouteRoute._addFileChildren(
  appNoticesRouteRouteChildren,
)

interface appPublicRequestsRouteRouteChildren {
  appPublicRequestsRequestIdRoute: typeof appPublicRequestsRequestIdRoute
  appPublicRequestsIndexRoute: typeof appPublicRequestsIndexRoute
}

const appPublicRequestsRouteRouteChildren: appPublicRequestsRouteRouteChildren =
  {
    appPublicRequestsRequestIdRoute: appPublicRequestsRequestIdRoute,
    appPublicRequestsIndexRoute: appPublicRequestsIndexRoute,
  }

const appPublicRequestsRouteRouteWithChildren =
  appPublicRequestsRouteRoute._addFileChildren(
    appPublicRequestsRouteRouteChildren,
  )

interface appSprayScheduleRouteRouteChildren {
  appSprayScheduleSprayScheduleIdRoute: typeof appSprayScheduleSprayScheduleIdRoute
  appSprayScheduleCreateRoute: typeof appSprayScheduleCreateRoute
  appSprayScheduleIndexRoute: typeof appSprayScheduleIndexRoute
  appSprayScheduleSprayScheduleIdEditRoute: typeof appSprayScheduleSprayScheduleIdEditRoute
}

const appSprayScheduleRouteRouteChildren: appSprayScheduleRouteRouteChildren = {
  appSprayScheduleSprayScheduleIdRoute: appSprayScheduleSprayScheduleIdRoute,
  appSprayScheduleCreateRoute: appSprayScheduleCreateRoute,
  appSprayScheduleIndexRoute: appSprayScheduleIndexRoute,
  appSprayScheduleSprayScheduleIdEditRoute:
    appSprayScheduleSprayScheduleIdEditRoute,
}

const appSprayScheduleRouteRouteWithChildren =
  appSprayScheduleRouteRoute._addFileChildren(
    appSprayScheduleRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appCategoriesRouteRoute: typeof appCategoriesRouteRouteWithChildren
  appDocumentCategoriesRouteRoute: typeof appDocumentCategoriesRouteRouteWithChildren
  appDocumentsRouteRoute: typeof appDocumentsRouteRouteWithChildren
  appInsecticidesRouteRoute: typeof appInsecticidesRouteRouteWithChildren
  appJobPostingsRouteRoute: typeof appJobPostingsRouteRouteWithChildren
  appMeetingsRouteRoute: typeof appMeetingsRouteRouteWithChildren
  appNoticesRouteRoute: typeof appNoticesRouteRouteWithChildren
  appPublicRequestsRouteRoute: typeof appPublicRequestsRouteRouteWithChildren
  appSprayScheduleRouteRoute: typeof appSprayScheduleRouteRouteWithChildren
  appIndexRoute: typeof appIndexRoute
  appWeeklyActivityIndexRoute: typeof appWeeklyActivityIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appCategoriesRouteRoute: appCategoriesRouteRouteWithChildren,
  appDocumentCategoriesRouteRoute: appDocumentCategoriesRouteRouteWithChildren,
  appDocumentsRouteRoute: appDocumentsRouteRouteWithChildren,
  appInsecticidesRouteRoute: appInsecticidesRouteRouteWithChildren,
  appJobPostingsRouteRoute: appJobPostingsRouteRouteWithChildren,
  appMeetingsRouteRoute: appMeetingsRouteRouteWithChildren,
  appNoticesRouteRoute: appNoticesRouteRouteWithChildren,
  appPublicRequestsRouteRoute: appPublicRequestsRouteRouteWithChildren,
  appSprayScheduleRouteRoute: appSprayScheduleRouteRouteWithChildren,
  appIndexRoute: appIndexRoute,
  appWeeklyActivityIndexRoute: appWeeklyActivityIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
