/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SprayScheduleRouteImport } from './routes/spray-schedule'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as MosquitoSurveillanceRouteImport } from './routes/mosquito-surveillance'
import { Route as MosquitoControlRouteImport } from './routes/mosquito-control'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticesIndexRouteImport } from './routes/notices/index'
import { Route as JobOpportunitiesIndexRouteImport } from './routes/job-opportunities/index'
import { Route as NoticesTransparencyRouteImport } from './routes/notices/transparency'
import { Route as NoticesMeetingsRouteImport } from './routes/notices/meetings'
import { Route as NoticesArchiveRouteImport } from './routes/notices/archive'
import { Route as NoticesNoticeIdRouteImport } from './routes/notices/$noticeId'
import { Route as MosquitoSurveillanceWeeklyActivityRouteImport } from './routes/mosquito-surveillance/weekly-activity'
import { Route as MosquitoSurveillanceMunicipalPacketRouteImport } from './routes/mosquito-surveillance/municipal-packet'
import { Route as MosquitoSurveillanceMosquitoSourceChecklistRouteImport } from './routes/mosquito-surveillance/mosquito-source-checklist'
import { Route as MosquitoControlSprayScheduleRouteImport } from './routes/mosquito-control/spray-schedule'
import { Route as MosquitoControlSprayNoticeRouteImport } from './routes/mosquito-control/spray-notice'
import { Route as MosquitoControlMosquitoControlProductsRouteImport } from './routes/mosquito-control/mosquito-control-products'
import { Route as MosquitoControlHowWeControlMosquitoesRouteImport } from './routes/mosquito-control/how-we-control-mosquitoes'
import { Route as MosquitoControlAerialLarvicidingNoticeRouteImport } from './routes/mosquito-control/aerial-larviciding-notice'
import { Route as JobOpportunitiesPostingIdRouteImport } from './routes/job-opportunities/$postingId'
import { Route as ContactWaterManagementRequestsRouteImport } from './routes/contact/water-management-requests'
import { Route as ContactServiceRequestRouteImport } from './routes/contact/service-request'
import { Route as ContactRequestSuccessRouteImport } from './routes/contact/request-success'
import { Route as ContactMosquitofishRequestsRouteImport } from './routes/contact/mosquitofish-requests'
import { Route as ContactContactUsRouteImport } from './routes/contact/contact-us'
import { Route as ContactAdultMosquitoRequestsRouteImport } from './routes/contact/adult-mosquito-requests'
import { Route as AboutMosquitoControlProductsRouteImport } from './routes/about/mosquito-control-products'
import { Route as AboutMissionStatementRouteImport } from './routes/about/mission-statement'
import { Route as AboutMissionRouteImport } from './routes/about/mission'
import { Route as AboutLeadershipRouteImport } from './routes/about/leadership'
import { Route as AboutHowWeControlMosquitoesRouteImport } from './routes/about/how-we-control-mosquitoes'
import { Route as AboutJobOpportunitiesIndexRouteImport } from './routes/about/job-opportunities/index'
import { Route as AboutJobOpportunitiesPostingIdRouteImport } from './routes/about/job-opportunities/$postingId'

const SprayScheduleRoute = SprayScheduleRouteImport.update({
  id: '/spray-schedule',
  path: '/spray-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const MosquitoSurveillanceRoute = MosquitoSurveillanceRouteImport.update({
  id: '/mosquito-surveillance',
  path: '/mosquito-surveillance',
  getParentRoute: () => rootRouteImport,
} as any)
const MosquitoControlRoute = MosquitoControlRouteImport.update({
  id: '/mosquito-control',
  path: '/mosquito-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesIndexRoute = NoticesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoticesRoute,
} as any)
const JobOpportunitiesIndexRoute = JobOpportunitiesIndexRouteImport.update({
  id: '/job-opportunities/',
  path: '/job-opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesTransparencyRoute = NoticesTransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => NoticesRoute,
} as any)
const NoticesMeetingsRoute = NoticesMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => NoticesRoute,
} as any)
const NoticesArchiveRoute = NoticesArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => NoticesRoute,
} as any)
const NoticesNoticeIdRoute = NoticesNoticeIdRouteImport.update({
  id: '/$noticeId',
  path: '/$noticeId',
  getParentRoute: () => NoticesRoute,
} as any)
const MosquitoSurveillanceWeeklyActivityRoute =
  MosquitoSurveillanceWeeklyActivityRouteImport.update({
    id: '/weekly-activity',
    path: '/weekly-activity',
    getParentRoute: () => MosquitoSurveillanceRoute,
  } as any)
const MosquitoSurveillanceMunicipalPacketRoute =
  MosquitoSurveillanceMunicipalPacketRouteImport.update({
    id: '/municipal-packet',
    path: '/municipal-packet',
    getParentRoute: () => MosquitoSurveillanceRoute,
  } as any)
const MosquitoSurveillanceMosquitoSourceChecklistRoute =
  MosquitoSurveillanceMosquitoSourceChecklistRouteImport.update({
    id: '/mosquito-source-checklist',
    path: '/mosquito-source-checklist',
    getParentRoute: () => MosquitoSurveillanceRoute,
  } as any)
const MosquitoControlSprayScheduleRoute =
  MosquitoControlSprayScheduleRouteImport.update({
    id: '/spray-schedule',
    path: '/spray-schedule',
    getParentRoute: () => MosquitoControlRoute,
  } as any)
const MosquitoControlSprayNoticeRoute =
  MosquitoControlSprayNoticeRouteImport.update({
    id: '/spray-notice',
    path: '/spray-notice',
    getParentRoute: () => MosquitoControlRoute,
  } as any)
const MosquitoControlMosquitoControlProductsRoute =
  MosquitoControlMosquitoControlProductsRouteImport.update({
    id: '/mosquito-control-products',
    path: '/mosquito-control-products',
    getParentRoute: () => MosquitoControlRoute,
  } as any)
const MosquitoControlHowWeControlMosquitoesRoute =
  MosquitoControlHowWeControlMosquitoesRouteImport.update({
    id: '/how-we-control-mosquitoes',
    path: '/how-we-control-mosquitoes',
    getParentRoute: () => MosquitoControlRoute,
  } as any)
const MosquitoControlAerialLarvicidingNoticeRoute =
  MosquitoControlAerialLarvicidingNoticeRouteImport.update({
    id: '/aerial-larviciding-notice',
    path: '/aerial-larviciding-notice',
    getParentRoute: () => MosquitoControlRoute,
  } as any)
const JobOpportunitiesPostingIdRoute =
  JobOpportunitiesPostingIdRouteImport.update({
    id: '/job-opportunities/$postingId',
    path: '/job-opportunities/$postingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactWaterManagementRequestsRoute =
  ContactWaterManagementRequestsRouteImport.update({
    id: '/water-management-requests',
    path: '/water-management-requests',
    getParentRoute: () => ContactRoute,
  } as any)
const ContactServiceRequestRoute = ContactServiceRequestRouteImport.update({
  id: '/service-request',
  path: '/service-request',
  getParentRoute: () => ContactRoute,
} as any)
const ContactRequestSuccessRoute = ContactRequestSuccessRouteImport.update({
  id: '/request-success',
  path: '/request-success',
  getParentRoute: () => ContactRoute,
} as any)
const ContactMosquitofishRequestsRoute =
  ContactMosquitofishRequestsRouteImport.update({
    id: '/mosquitofish-requests',
    path: '/mosquitofish-requests',
    getParentRoute: () => ContactRoute,
  } as any)
const ContactContactUsRoute = ContactContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => ContactRoute,
} as any)
const ContactAdultMosquitoRequestsRoute =
  ContactAdultMosquitoRequestsRouteImport.update({
    id: '/adult-mosquito-requests',
    path: '/adult-mosquito-requests',
    getParentRoute: () => ContactRoute,
  } as any)
const AboutMosquitoControlProductsRoute =
  AboutMosquitoControlProductsRouteImport.update({
    id: '/mosquito-control-products',
    path: '/mosquito-control-products',
    getParentRoute: () => AboutRoute,
  } as any)
const AboutMissionStatementRoute = AboutMissionStatementRouteImport.update({
  id: '/mission-statement',
  path: '/mission-statement',
  getParentRoute: () => AboutRoute,
} as any)
const AboutMissionRoute = AboutMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => AboutRoute,
} as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => AboutRoute,
} as any)
const AboutHowWeControlMosquitoesRoute =
  AboutHowWeControlMosquitoesRouteImport.update({
    id: '/how-we-control-mosquitoes',
    path: '/how-we-control-mosquitoes',
    getParentRoute: () => AboutRoute,
  } as any)
const AboutJobOpportunitiesIndexRoute =
  AboutJobOpportunitiesIndexRouteImport.update({
    id: '/job-opportunities/',
    path: '/job-opportunities/',
    getParentRoute: () => AboutRoute,
  } as any)
const AboutJobOpportunitiesPostingIdRoute =
  AboutJobOpportunitiesPostingIdRouteImport.update({
    id: '/job-opportunities/$postingId',
    path: '/job-opportunities/$postingId',
    getParentRoute: () => AboutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRouteWithChildren
  '/mosquito-control': typeof MosquitoControlRouteWithChildren
  '/mosquito-surveillance': typeof MosquitoSurveillanceRouteWithChildren
  '/notices': typeof NoticesRouteWithChildren
  '/spray-schedule': typeof SprayScheduleRoute
  '/about/how-we-control-mosquitoes': typeof AboutHowWeControlMosquitoesRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/mission-statement': typeof AboutMissionStatementRoute
  '/about/mosquito-control-products': typeof AboutMosquitoControlProductsRoute
  '/contact/adult-mosquito-requests': typeof ContactAdultMosquitoRequestsRoute
  '/contact/contact-us': typeof ContactContactUsRoute
  '/contact/mosquitofish-requests': typeof ContactMosquitofishRequestsRoute
  '/contact/request-success': typeof ContactRequestSuccessRoute
  '/contact/service-request': typeof ContactServiceRequestRoute
  '/contact/water-management-requests': typeof ContactWaterManagementRequestsRoute
  '/job-opportunities/$postingId': typeof JobOpportunitiesPostingIdRoute
  '/mosquito-control/aerial-larviciding-notice': typeof MosquitoControlAerialLarvicidingNoticeRoute
  '/mosquito-control/how-we-control-mosquitoes': typeof MosquitoControlHowWeControlMosquitoesRoute
  '/mosquito-control/mosquito-control-products': typeof MosquitoControlMosquitoControlProductsRoute
  '/mosquito-control/spray-notice': typeof MosquitoControlSprayNoticeRoute
  '/mosquito-control/spray-schedule': typeof MosquitoControlSprayScheduleRoute
  '/mosquito-surveillance/mosquito-source-checklist': typeof MosquitoSurveillanceMosquitoSourceChecklistRoute
  '/mosquito-surveillance/municipal-packet': typeof MosquitoSurveillanceMunicipalPacketRoute
  '/mosquito-surveillance/weekly-activity': typeof MosquitoSurveillanceWeeklyActivityRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/notices/archive': typeof NoticesArchiveRoute
  '/notices/meetings': typeof NoticesMeetingsRoute
  '/notices/transparency': typeof NoticesTransparencyRoute
  '/job-opportunities/': typeof JobOpportunitiesIndexRoute
  '/notices/': typeof NoticesIndexRoute
  '/about/job-opportunities/$postingId': typeof AboutJobOpportunitiesPostingIdRoute
  '/about/job-opportunities/': typeof AboutJobOpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRouteWithChildren
  '/mosquito-control': typeof MosquitoControlRouteWithChildren
  '/mosquito-surveillance': typeof MosquitoSurveillanceRouteWithChildren
  '/spray-schedule': typeof SprayScheduleRoute
  '/about/how-we-control-mosquitoes': typeof AboutHowWeControlMosquitoesRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/mission-statement': typeof AboutMissionStatementRoute
  '/about/mosquito-control-products': typeof AboutMosquitoControlProductsRoute
  '/contact/adult-mosquito-requests': typeof ContactAdultMosquitoRequestsRoute
  '/contact/contact-us': typeof ContactContactUsRoute
  '/contact/mosquitofish-requests': typeof ContactMosquitofishRequestsRoute
  '/contact/request-success': typeof ContactRequestSuccessRoute
  '/contact/service-request': typeof ContactServiceRequestRoute
  '/contact/water-management-requests': typeof ContactWaterManagementRequestsRoute
  '/job-opportunities/$postingId': typeof JobOpportunitiesPostingIdRoute
  '/mosquito-control/aerial-larviciding-notice': typeof MosquitoControlAerialLarvicidingNoticeRoute
  '/mosquito-control/how-we-control-mosquitoes': typeof MosquitoControlHowWeControlMosquitoesRoute
  '/mosquito-control/mosquito-control-products': typeof MosquitoControlMosquitoControlProductsRoute
  '/mosquito-control/spray-notice': typeof MosquitoControlSprayNoticeRoute
  '/mosquito-control/spray-schedule': typeof MosquitoControlSprayScheduleRoute
  '/mosquito-surveillance/mosquito-source-checklist': typeof MosquitoSurveillanceMosquitoSourceChecklistRoute
  '/mosquito-surveillance/municipal-packet': typeof MosquitoSurveillanceMunicipalPacketRoute
  '/mosquito-surveillance/weekly-activity': typeof MosquitoSurveillanceWeeklyActivityRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/notices/archive': typeof NoticesArchiveRoute
  '/notices/meetings': typeof NoticesMeetingsRoute
  '/notices/transparency': typeof NoticesTransparencyRoute
  '/job-opportunities': typeof JobOpportunitiesIndexRoute
  '/notices': typeof NoticesIndexRoute
  '/about/job-opportunities/$postingId': typeof AboutJobOpportunitiesPostingIdRoute
  '/about/job-opportunities': typeof AboutJobOpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/contact': typeof ContactRouteWithChildren
  '/mosquito-control': typeof MosquitoControlRouteWithChildren
  '/mosquito-surveillance': typeof MosquitoSurveillanceRouteWithChildren
  '/notices': typeof NoticesRouteWithChildren
  '/spray-schedule': typeof SprayScheduleRoute
  '/about/how-we-control-mosquitoes': typeof AboutHowWeControlMosquitoesRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/mission-statement': typeof AboutMissionStatementRoute
  '/about/mosquito-control-products': typeof AboutMosquitoControlProductsRoute
  '/contact/adult-mosquito-requests': typeof ContactAdultMosquitoRequestsRoute
  '/contact/contact-us': typeof ContactContactUsRoute
  '/contact/mosquitofish-requests': typeof ContactMosquitofishRequestsRoute
  '/contact/request-success': typeof ContactRequestSuccessRoute
  '/contact/service-request': typeof ContactServiceRequestRoute
  '/contact/water-management-requests': typeof ContactWaterManagementRequestsRoute
  '/job-opportunities/$postingId': typeof JobOpportunitiesPostingIdRoute
  '/mosquito-control/aerial-larviciding-notice': typeof MosquitoControlAerialLarvicidingNoticeRoute
  '/mosquito-control/how-we-control-mosquitoes': typeof MosquitoControlHowWeControlMosquitoesRoute
  '/mosquito-control/mosquito-control-products': typeof MosquitoControlMosquitoControlProductsRoute
  '/mosquito-control/spray-notice': typeof MosquitoControlSprayNoticeRoute
  '/mosquito-control/spray-schedule': typeof MosquitoControlSprayScheduleRoute
  '/mosquito-surveillance/mosquito-source-checklist': typeof MosquitoSurveillanceMosquitoSourceChecklistRoute
  '/mosquito-surveillance/municipal-packet': typeof MosquitoSurveillanceMunicipalPacketRoute
  '/mosquito-surveillance/weekly-activity': typeof MosquitoSurveillanceWeeklyActivityRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/notices/archive': typeof NoticesArchiveRoute
  '/notices/meetings': typeof NoticesMeetingsRoute
  '/notices/transparency': typeof NoticesTransparencyRoute
  '/job-opportunities/': typeof JobOpportunitiesIndexRoute
  '/notices/': typeof NoticesIndexRoute
  '/about/job-opportunities/$postingId': typeof AboutJobOpportunitiesPostingIdRoute
  '/about/job-opportunities/': typeof AboutJobOpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/mosquito-control'
    | '/mosquito-surveillance'
    | '/notices'
    | '/spray-schedule'
    | '/about/how-we-control-mosquitoes'
    | '/about/leadership'
    | '/about/mission'
    | '/about/mission-statement'
    | '/about/mosquito-control-products'
    | '/contact/adult-mosquito-requests'
    | '/contact/contact-us'
    | '/contact/mosquitofish-requests'
    | '/contact/request-success'
    | '/contact/service-request'
    | '/contact/water-management-requests'
    | '/job-opportunities/$postingId'
    | '/mosquito-control/aerial-larviciding-notice'
    | '/mosquito-control/how-we-control-mosquitoes'
    | '/mosquito-control/mosquito-control-products'
    | '/mosquito-control/spray-notice'
    | '/mosquito-control/spray-schedule'
    | '/mosquito-surveillance/mosquito-source-checklist'
    | '/mosquito-surveillance/municipal-packet'
    | '/mosquito-surveillance/weekly-activity'
    | '/notices/$noticeId'
    | '/notices/archive'
    | '/notices/meetings'
    | '/notices/transparency'
    | '/job-opportunities/'
    | '/notices/'
    | '/about/job-opportunities/$postingId'
    | '/about/job-opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/mosquito-control'
    | '/mosquito-surveillance'
    | '/spray-schedule'
    | '/about/how-we-control-mosquitoes'
    | '/about/leadership'
    | '/about/mission'
    | '/about/mission-statement'
    | '/about/mosquito-control-products'
    | '/contact/adult-mosquito-requests'
    | '/contact/contact-us'
    | '/contact/mosquitofish-requests'
    | '/contact/request-success'
    | '/contact/service-request'
    | '/contact/water-management-requests'
    | '/job-opportunities/$postingId'
    | '/mosquito-control/aerial-larviciding-notice'
    | '/mosquito-control/how-we-control-mosquitoes'
    | '/mosquito-control/mosquito-control-products'
    | '/mosquito-control/spray-notice'
    | '/mosquito-control/spray-schedule'
    | '/mosquito-surveillance/mosquito-source-checklist'
    | '/mosquito-surveillance/municipal-packet'
    | '/mosquito-surveillance/weekly-activity'
    | '/notices/$noticeId'
    | '/notices/archive'
    | '/notices/meetings'
    | '/notices/transparency'
    | '/job-opportunities'
    | '/notices'
    | '/about/job-opportunities/$postingId'
    | '/about/job-opportunities'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/mosquito-control'
    | '/mosquito-surveillance'
    | '/notices'
    | '/spray-schedule'
    | '/about/how-we-control-mosquitoes'
    | '/about/leadership'
    | '/about/mission'
    | '/about/mission-statement'
    | '/about/mosquito-control-products'
    | '/contact/adult-mosquito-requests'
    | '/contact/contact-us'
    | '/contact/mosquitofish-requests'
    | '/contact/request-success'
    | '/contact/service-request'
    | '/contact/water-management-requests'
    | '/job-opportunities/$postingId'
    | '/mosquito-control/aerial-larviciding-notice'
    | '/mosquito-control/how-we-control-mosquitoes'
    | '/mosquito-control/mosquito-control-products'
    | '/mosquito-control/spray-notice'
    | '/mosquito-control/spray-schedule'
    | '/mosquito-surveillance/mosquito-source-checklist'
    | '/mosquito-surveillance/municipal-packet'
    | '/mosquito-surveillance/weekly-activity'
    | '/notices/$noticeId'
    | '/notices/archive'
    | '/notices/meetings'
    | '/notices/transparency'
    | '/job-opportunities/'
    | '/notices/'
    | '/about/job-opportunities/$postingId'
    | '/about/job-opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ContactRoute: typeof ContactRouteWithChildren
  MosquitoControlRoute: typeof MosquitoControlRouteWithChildren
  MosquitoSurveillanceRoute: typeof MosquitoSurveillanceRouteWithChildren
  NoticesRoute: typeof NoticesRouteWithChildren
  SprayScheduleRoute: typeof SprayScheduleRoute
  JobOpportunitiesPostingIdRoute: typeof JobOpportunitiesPostingIdRoute
  JobOpportunitiesIndexRoute: typeof JobOpportunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spray-schedule': {
      id: '/spray-schedule'
      path: '/spray-schedule'
      fullPath: '/spray-schedule'
      preLoaderRoute: typeof SprayScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosquito-surveillance': {
      id: '/mosquito-surveillance'
      path: '/mosquito-surveillance'
      fullPath: '/mosquito-surveillance'
      preLoaderRoute: typeof MosquitoSurveillanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosquito-control': {
      id: '/mosquito-control'
      path: '/mosquito-control'
      fullPath: '/mosquito-control'
      preLoaderRoute: typeof MosquitoControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/': {
      id: '/notices/'
      path: '/'
      fullPath: '/notices/'
      preLoaderRoute: typeof NoticesIndexRouteImport
      parentRoute: typeof NoticesRoute
    }
    '/job-opportunities/': {
      id: '/job-opportunities/'
      path: '/job-opportunities'
      fullPath: '/job-opportunities/'
      preLoaderRoute: typeof JobOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/transparency': {
      id: '/notices/transparency'
      path: '/transparency'
      fullPath: '/notices/transparency'
      preLoaderRoute: typeof NoticesTransparencyRouteImport
      parentRoute: typeof NoticesRoute
    }
    '/notices/meetings': {
      id: '/notices/meetings'
      path: '/meetings'
      fullPath: '/notices/meetings'
      preLoaderRoute: typeof NoticesMeetingsRouteImport
      parentRoute: typeof NoticesRoute
    }
    '/notices/archive': {
      id: '/notices/archive'
      path: '/archive'
      fullPath: '/notices/archive'
      preLoaderRoute: typeof NoticesArchiveRouteImport
      parentRoute: typeof NoticesRoute
    }
    '/notices/$noticeId': {
      id: '/notices/$noticeId'
      path: '/$noticeId'
      fullPath: '/notices/$noticeId'
      preLoaderRoute: typeof NoticesNoticeIdRouteImport
      parentRoute: typeof NoticesRoute
    }
    '/mosquito-surveillance/weekly-activity': {
      id: '/mosquito-surveillance/weekly-activity'
      path: '/weekly-activity'
      fullPath: '/mosquito-surveillance/weekly-activity'
      preLoaderRoute: typeof MosquitoSurveillanceWeeklyActivityRouteImport
      parentRoute: typeof MosquitoSurveillanceRoute
    }
    '/mosquito-surveillance/municipal-packet': {
      id: '/mosquito-surveillance/municipal-packet'
      path: '/municipal-packet'
      fullPath: '/mosquito-surveillance/municipal-packet'
      preLoaderRoute: typeof MosquitoSurveillanceMunicipalPacketRouteImport
      parentRoute: typeof MosquitoSurveillanceRoute
    }
    '/mosquito-surveillance/mosquito-source-checklist': {
      id: '/mosquito-surveillance/mosquito-source-checklist'
      path: '/mosquito-source-checklist'
      fullPath: '/mosquito-surveillance/mosquito-source-checklist'
      preLoaderRoute: typeof MosquitoSurveillanceMosquitoSourceChecklistRouteImport
      parentRoute: typeof MosquitoSurveillanceRoute
    }
    '/mosquito-control/spray-schedule': {
      id: '/mosquito-control/spray-schedule'
      path: '/spray-schedule'
      fullPath: '/mosquito-control/spray-schedule'
      preLoaderRoute: typeof MosquitoControlSprayScheduleRouteImport
      parentRoute: typeof MosquitoControlRoute
    }
    '/mosquito-control/spray-notice': {
      id: '/mosquito-control/spray-notice'
      path: '/spray-notice'
      fullPath: '/mosquito-control/spray-notice'
      preLoaderRoute: typeof MosquitoControlSprayNoticeRouteImport
      parentRoute: typeof MosquitoControlRoute
    }
    '/mosquito-control/mosquito-control-products': {
      id: '/mosquito-control/mosquito-control-products'
      path: '/mosquito-control-products'
      fullPath: '/mosquito-control/mosquito-control-products'
      preLoaderRoute: typeof MosquitoControlMosquitoControlProductsRouteImport
      parentRoute: typeof MosquitoControlRoute
    }
    '/mosquito-control/how-we-control-mosquitoes': {
      id: '/mosquito-control/how-we-control-mosquitoes'
      path: '/how-we-control-mosquitoes'
      fullPath: '/mosquito-control/how-we-control-mosquitoes'
      preLoaderRoute: typeof MosquitoControlHowWeControlMosquitoesRouteImport
      parentRoute: typeof MosquitoControlRoute
    }
    '/mosquito-control/aerial-larviciding-notice': {
      id: '/mosquito-control/aerial-larviciding-notice'
      path: '/aerial-larviciding-notice'
      fullPath: '/mosquito-control/aerial-larviciding-notice'
      preLoaderRoute: typeof MosquitoControlAerialLarvicidingNoticeRouteImport
      parentRoute: typeof MosquitoControlRoute
    }
    '/job-opportunities/$postingId': {
      id: '/job-opportunities/$postingId'
      path: '/job-opportunities/$postingId'
      fullPath: '/job-opportunities/$postingId'
      preLoaderRoute: typeof JobOpportunitiesPostingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/water-management-requests': {
      id: '/contact/water-management-requests'
      path: '/water-management-requests'
      fullPath: '/contact/water-management-requests'
      preLoaderRoute: typeof ContactWaterManagementRequestsRouteImport
      parentRoute: typeof ContactRoute
    }
    '/contact/service-request': {
      id: '/contact/service-request'
      path: '/service-request'
      fullPath: '/contact/service-request'
      preLoaderRoute: typeof ContactServiceRequestRouteImport
      parentRoute: typeof ContactRoute
    }
    '/contact/request-success': {
      id: '/contact/request-success'
      path: '/request-success'
      fullPath: '/contact/request-success'
      preLoaderRoute: typeof ContactRequestSuccessRouteImport
      parentRoute: typeof ContactRoute
    }
    '/contact/mosquitofish-requests': {
      id: '/contact/mosquitofish-requests'
      path: '/mosquitofish-requests'
      fullPath: '/contact/mosquitofish-requests'
      preLoaderRoute: typeof ContactMosquitofishRequestsRouteImport
      parentRoute: typeof ContactRoute
    }
    '/contact/contact-us': {
      id: '/contact/contact-us'
      path: '/contact-us'
      fullPath: '/contact/contact-us'
      preLoaderRoute: typeof ContactContactUsRouteImport
      parentRoute: typeof ContactRoute
    }
    '/contact/adult-mosquito-requests': {
      id: '/contact/adult-mosquito-requests'
      path: '/adult-mosquito-requests'
      fullPath: '/contact/adult-mosquito-requests'
      preLoaderRoute: typeof ContactAdultMosquitoRequestsRouteImport
      parentRoute: typeof ContactRoute
    }
    '/about/mosquito-control-products': {
      id: '/about/mosquito-control-products'
      path: '/mosquito-control-products'
      fullPath: '/about/mosquito-control-products'
      preLoaderRoute: typeof AboutMosquitoControlProductsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/mission-statement': {
      id: '/about/mission-statement'
      path: '/mission-statement'
      fullPath: '/about/mission-statement'
      preLoaderRoute: typeof AboutMissionStatementRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/mission': {
      id: '/about/mission'
      path: '/mission'
      fullPath: '/about/mission'
      preLoaderRoute: typeof AboutMissionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/leadership': {
      id: '/about/leadership'
      path: '/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/how-we-control-mosquitoes': {
      id: '/about/how-we-control-mosquitoes'
      path: '/how-we-control-mosquitoes'
      fullPath: '/about/how-we-control-mosquitoes'
      preLoaderRoute: typeof AboutHowWeControlMosquitoesRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/job-opportunities/': {
      id: '/about/job-opportunities/'
      path: '/job-opportunities'
      fullPath: '/about/job-opportunities/'
      preLoaderRoute: typeof AboutJobOpportunitiesIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/job-opportunities/$postingId': {
      id: '/about/job-opportunities/$postingId'
      path: '/job-opportunities/$postingId'
      fullPath: '/about/job-opportunities/$postingId'
      preLoaderRoute: typeof AboutJobOpportunitiesPostingIdRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutHowWeControlMosquitoesRoute: typeof AboutHowWeControlMosquitoesRoute
  AboutLeadershipRoute: typeof AboutLeadershipRoute
  AboutMissionRoute: typeof AboutMissionRoute
  AboutMissionStatementRoute: typeof AboutMissionStatementRoute
  AboutMosquitoControlProductsRoute: typeof AboutMosquitoControlProductsRoute
  AboutJobOpportunitiesPostingIdRoute: typeof AboutJobOpportunitiesPostingIdRoute
  AboutJobOpportunitiesIndexRoute: typeof AboutJobOpportunitiesIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutHowWeControlMosquitoesRoute: AboutHowWeControlMosquitoesRoute,
  AboutLeadershipRoute: AboutLeadershipRoute,
  AboutMissionRoute: AboutMissionRoute,
  AboutMissionStatementRoute: AboutMissionStatementRoute,
  AboutMosquitoControlProductsRoute: AboutMosquitoControlProductsRoute,
  AboutJobOpportunitiesPostingIdRoute: AboutJobOpportunitiesPostingIdRoute,
  AboutJobOpportunitiesIndexRoute: AboutJobOpportunitiesIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface ContactRouteChildren {
  ContactAdultMosquitoRequestsRoute: typeof ContactAdultMosquitoRequestsRoute
  ContactContactUsRoute: typeof ContactContactUsRoute
  ContactMosquitofishRequestsRoute: typeof ContactMosquitofishRequestsRoute
  ContactRequestSuccessRoute: typeof ContactRequestSuccessRoute
  ContactServiceRequestRoute: typeof ContactServiceRequestRoute
  ContactWaterManagementRequestsRoute: typeof ContactWaterManagementRequestsRoute
}

const ContactRouteChildren: ContactRouteChildren = {
  ContactAdultMosquitoRequestsRoute: ContactAdultMosquitoRequestsRoute,
  ContactContactUsRoute: ContactContactUsRoute,
  ContactMosquitofishRequestsRoute: ContactMosquitofishRequestsRoute,
  ContactRequestSuccessRoute: ContactRequestSuccessRoute,
  ContactServiceRequestRoute: ContactServiceRequestRoute,
  ContactWaterManagementRequestsRoute: ContactWaterManagementRequestsRoute,
}

const ContactRouteWithChildren =
  ContactRoute._addFileChildren(ContactRouteChildren)

interface MosquitoControlRouteChildren {
  MosquitoControlAerialLarvicidingNoticeRoute: typeof MosquitoControlAerialLarvicidingNoticeRoute
  MosquitoControlHowWeControlMosquitoesRoute: typeof MosquitoControlHowWeControlMosquitoesRoute
  MosquitoControlMosquitoControlProductsRoute: typeof MosquitoControlMosquitoControlProductsRoute
  MosquitoControlSprayNoticeRoute: typeof MosquitoControlSprayNoticeRoute
  MosquitoControlSprayScheduleRoute: typeof MosquitoControlSprayScheduleRoute
}

const MosquitoControlRouteChildren: MosquitoControlRouteChildren = {
  MosquitoControlAerialLarvicidingNoticeRoute:
    MosquitoControlAerialLarvicidingNoticeRoute,
  MosquitoControlHowWeControlMosquitoesRoute:
    MosquitoControlHowWeControlMosquitoesRoute,
  MosquitoControlMosquitoControlProductsRoute:
    MosquitoControlMosquitoControlProductsRoute,
  MosquitoControlSprayNoticeRoute: MosquitoControlSprayNoticeRoute,
  MosquitoControlSprayScheduleRoute: MosquitoControlSprayScheduleRoute,
}

const MosquitoControlRouteWithChildren = MosquitoControlRoute._addFileChildren(
  MosquitoControlRouteChildren,
)

interface MosquitoSurveillanceRouteChildren {
  MosquitoSurveillanceMosquitoSourceChecklistRoute: typeof MosquitoSurveillanceMosquitoSourceChecklistRoute
  MosquitoSurveillanceMunicipalPacketRoute: typeof MosquitoSurveillanceMunicipalPacketRoute
  MosquitoSurveillanceWeeklyActivityRoute: typeof MosquitoSurveillanceWeeklyActivityRoute
}

const MosquitoSurveillanceRouteChildren: MosquitoSurveillanceRouteChildren = {
  MosquitoSurveillanceMosquitoSourceChecklistRoute:
    MosquitoSurveillanceMosquitoSourceChecklistRoute,
  MosquitoSurveillanceMunicipalPacketRoute:
    MosquitoSurveillanceMunicipalPacketRoute,
  MosquitoSurveillanceWeeklyActivityRoute:
    MosquitoSurveillanceWeeklyActivityRoute,
}

const MosquitoSurveillanceRouteWithChildren =
  MosquitoSurveillanceRoute._addFileChildren(MosquitoSurveillanceRouteChildren)

interface NoticesRouteChildren {
  NoticesNoticeIdRoute: typeof NoticesNoticeIdRoute
  NoticesArchiveRoute: typeof NoticesArchiveRoute
  NoticesMeetingsRoute: typeof NoticesMeetingsRoute
  NoticesTransparencyRoute: typeof NoticesTransparencyRoute
  NoticesIndexRoute: typeof NoticesIndexRoute
}

const NoticesRouteChildren: NoticesRouteChildren = {
  NoticesNoticeIdRoute: NoticesNoticeIdRoute,
  NoticesArchiveRoute: NoticesArchiveRoute,
  NoticesMeetingsRoute: NoticesMeetingsRoute,
  NoticesTransparencyRoute: NoticesTransparencyRoute,
  NoticesIndexRoute: NoticesIndexRoute,
}

const NoticesRouteWithChildren =
  NoticesRoute._addFileChildren(NoticesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ContactRoute: ContactRouteWithChildren,
  MosquitoControlRoute: MosquitoControlRouteWithChildren,
  MosquitoSurveillanceRoute: MosquitoSurveillanceRouteWithChildren,
  NoticesRoute: NoticesRouteWithChildren,
  SprayScheduleRoute: SprayScheduleRoute,
  JobOpportunitiesPostingIdRoute: JobOpportunitiesPostingIdRoute,
  JobOpportunitiesIndexRoute: JobOpportunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
