/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticesIndexRouteImport } from './routes/notices/index'
import { Route as NoticesArchiveRouteImport } from './routes/notices/archive'
import { Route as NoticesNoticeIdRouteImport } from './routes/notices/$noticeId'

const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesIndexRoute = NoticesIndexRouteImport.update({
  id: '/notices/',
  path: '/notices/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesArchiveRoute = NoticesArchiveRouteImport.update({
  id: '/notices/archive',
  path: '/notices/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesNoticeIdRoute = NoticesNoticeIdRouteImport.update({
  id: '/notices/$noticeId',
  path: '/notices/$noticeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meetings': typeof MeetingsRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/notices/archive': typeof NoticesArchiveRoute
  '/notices': typeof NoticesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meetings': typeof MeetingsRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/notices/archive': typeof NoticesArchiveRoute
  '/notices': typeof NoticesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meetings': typeof MeetingsRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/notices/archive': typeof NoticesArchiveRoute
  '/notices/': typeof NoticesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meetings'
    | '/notices/$noticeId'
    | '/notices/archive'
    | '/notices'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meetings' | '/notices/$noticeId' | '/notices/archive' | '/notices'
  id:
    | '__root__'
    | '/'
    | '/meetings'
    | '/notices/$noticeId'
    | '/notices/archive'
    | '/notices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeetingsRoute: typeof MeetingsRoute
  NoticesNoticeIdRoute: typeof NoticesNoticeIdRoute
  NoticesArchiveRoute: typeof NoticesArchiveRoute
  NoticesIndexRoute: typeof NoticesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/': {
      id: '/notices/'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/archive': {
      id: '/notices/archive'
      path: '/notices/archive'
      fullPath: '/notices/archive'
      preLoaderRoute: typeof NoticesArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/$noticeId': {
      id: '/notices/$noticeId'
      path: '/notices/$noticeId'
      fullPath: '/notices/$noticeId'
      preLoaderRoute: typeof NoticesNoticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeetingsRoute: MeetingsRoute,
  NoticesNoticeIdRoute: NoticesNoticeIdRoute,
  NoticesArchiveRoute: NoticesArchiveRoute,
  NoticesIndexRoute: NoticesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
